// Market sector configurations
export const SECTOR_CONFIGS = {
  stocks: {
    label: 'Stocks',
    marketOverview: [
      {
        title: 'Technology',
        symbols: [
          { s: 'NASDAQ:AAPL', d: 'Apple' },
          { s: 'NASDAQ:MSFT', d: 'Microsoft' },
          { s: 'NASDAQ:GOOGL', d: 'Alphabet' },
          { s: 'NASDAQ:META', d: 'Meta' },
          { s: 'NASDAQ:NVDA', d: 'NVIDIA' },
          { s: 'NASDAQ:TSLA', d: 'Tesla' },
        ],
      },
      {
        title: 'Financial',
        symbols: [
          { s: 'NYSE:JPM', d: 'JPMorgan' },
          { s: 'NYSE:BAC', d: 'Bank of America' },
          { s: 'NYSE:WFC', d: 'Wells Fargo' },
          { s: 'NYSE:GS', d: 'Goldman Sachs' },
          { s: 'NYSE:V', d: 'Visa' },
          { s: 'NYSE:MA', d: 'Mastercard' },
        ],
      },
    ],
    heatmapWidget: 'stock-heatmap',
    heatmapDataSource: 'SPX500',
    marketData: [
      { description: 'Apple Inc', proName: 'NASDAQ:AAPL' },
      { description: 'Microsoft Corporation', proName: 'NASDAQ:MSFT' },
      { description: 'NVIDIA Corporation', proName: 'NASDAQ:NVDA' },
      { description: 'Amazon.com Inc', proName: 'NASDAQ:AMZN' },
      { description: 'Alphabet Inc Class A', proName: 'NASDAQ:GOOGL' },
      { description: 'Meta Platforms Inc', proName: 'NASDAQ:META' },
      { description: 'Tesla, Inc.', proName: 'NASDAQ:TSLA' },
      { description: 'Berkshire Hathaway Inc', proName: 'NYSE:BRK.B' },
      { description: 'JPMorgan Chase & Co', proName: 'NYSE:JPM' },
      { description: 'Johnson & Johnson', proName: 'NYSE:JNJ' },
      { description: 'Visa Inc', proName: 'NYSE:V' },
      { description: 'Walmart Inc', proName: 'NYSE:WMT' },
      { description: 'Exxon Mobil Corporation', proName: 'NYSE:XOM' },
      { description: 'UnitedHealth Group Inc', proName: 'NYSE:UNH' },
      { description: 'Procter & Gamble Co', proName: 'NYSE:PG' },
      { description: 'Mastercard Inc', proName: 'NYSE:MA' },
      { description: 'Home Depot Inc', proName: 'NYSE:HD' },
      { description: 'Chevron Corporation', proName: 'NYSE:CVX' },
      { description: 'Coca-Cola Company', proName: 'NYSE:KO' },
      { description: 'PepsiCo Inc', proName: 'NASDAQ:PEP' },
      { description: 'Bank of America Corp', proName: 'NYSE:BAC' },
      { description: 'Netflix Inc', proName: 'NASDAQ:NFLX' },
      { description: 'Adobe Inc', proName: 'NASDAQ:ADBE' },
      { description: 'Salesforce Inc', proName: 'NYSE:CRM' },
    ],
    currencies: ['USD', 'EUR', 'GBP', 'JPY'],
    advancedChart: 'NASDAQ:AAPL',
  },
  forex: {
    label: 'Forex',
    marketOverview: [
      {
        title: 'Major Pairs',
        symbols: [
          { s: 'FX_IDC:EURUSD', d: 'EUR/USD' },
          { s: 'FX_IDC:GBPUSD', d: 'GBP/USD' },
          { s: 'FX_IDC:USDJPY', d: 'USD/JPY' },
          { s: 'FX_IDC:USDCHF', d: 'USD/CHF' },
          { s: 'FX_IDC:AUDUSD', d: 'AUD/USD' },
          { s: 'FX_IDC:USDCAD', d: 'USD/CAD' },
        ],
      },
      {
        title: 'Cross Pairs',
        symbols: [
          { s: 'FX_IDC:EURGBP', d: 'EUR/GBP' },
          { s: 'FX_IDC:EURJPY', d: 'EUR/JPY' },
          { s: 'FX_IDC:GBPJPY', d: 'GBP/JPY' },
          { s: 'FX_IDC:EURCHF', d: 'EUR/CHF' },
          { s: 'FX_IDC:AUDJPY', d: 'AUD/JPY' },
          { s: 'FX_IDC:NZDUSD', d: 'NZD/USD' },
        ],
      },
    ],
    heatmapWidget: 'forex-heat-map',
    heatmapDataSource: null,
    marketData: [
      { description: 'EUR/USD', proName: 'FX_IDC:EURUSD' },
      { description: 'GBP/USD', proName: 'FX_IDC:GBPUSD' },
      { description: 'USD/JPY', proName: 'FX_IDC:USDJPY' },
      { description: 'USD/CHF', proName: 'FX_IDC:USDCHF' },
      { description: 'AUD/USD', proName: 'FX_IDC:AUDUSD' },
      { description: 'USD/CAD', proName: 'FX_IDC:USDCAD' },
      { description: 'NZD/USD', proName: 'FX_IDC:NZDUSD' },
      { description: 'EUR/GBP', proName: 'FX_IDC:EURGBP' },
      { description: 'EUR/JPY', proName: 'FX_IDC:EURJPY' },
      { description: 'GBP/JPY', proName: 'FX_IDC:GBPJPY' },
      { description: 'EUR/CHF', proName: 'FX_IDC:EURCHF' },
      { description: 'AUD/JPY', proName: 'FX_IDC:AUDJPY' },
      { description: 'GBP/CHF', proName: 'FX_IDC:GBPCHF' },
      { description: 'EUR/AUD', proName: 'FX_IDC:EURAUD' },
      { description: 'USD/CNY', proName: 'FX_IDC:USDCNY' },
      { description: 'USD/HKD', proName: 'FX_IDC:USDHKD' },
      { description: 'USD/SGD', proName: 'FX_IDC:USDSGD' },
      { description: 'USD/MXN', proName: 'FX_IDC:USDMXN' },
      { description: 'EUR/CAD', proName: 'FX_IDC:EURCAD' },
      { description: 'GBP/AUD', proName: 'FX_IDC:GBPAUD' },
      { description: 'AUD/CAD', proName: 'FX_IDC:AUDCAD' },
      { description: 'NZD/JPY', proName: 'FX_IDC:NZDJPY' },
      { description: 'CAD/JPY', proName: 'FX_IDC:CADJPY' },
      { description: 'CHF/JPY', proName: 'FX_IDC:CHFJPY' },
    ],
    currencies: ['USD', 'EUR', 'GBP', 'JPY', 'CHF', 'AUD', 'CAD', 'NZD'],
    advancedChart: 'FX_IDC:EURUSD',
  },
  crypto: {
    label: 'Cryptocurrency',
    marketOverview: [
      {
        title: 'Top Crypto',
        symbols: [
          { s: 'BINANCE:BTCUSDT', d: 'Bitcoin' },
          { s: 'BINANCE:ETHUSDT', d: 'Ethereum' },
          { s: 'BINANCE:BNBUSDT', d: 'BNB' },
          { s: 'BINANCE:XRPUSDT', d: 'XRP' },
          { s: 'BINANCE:ADAUSDT', d: 'Cardano' },
          { s: 'BINANCE:SOLUSDT', d: 'Solana' },
        ],
      },
      {
        title: 'Alt Coins',
        symbols: [
          { s: 'BINANCE:DOGEUSDT', d: 'Dogecoin' },
          { s: 'BINANCE:MATICUSDT', d: 'Polygon' },
          { s: 'BINANCE:DOTUSDT', d: 'Polkadot' },
          { s: 'BINANCE:AVAXUSDT', d: 'Avalanche' },
          { s: 'BINANCE:LINKUSDT', d: 'Chainlink' },
          { s: 'BINANCE:UNIUSDT', d: 'Uniswap' },
        ],
      },
    ],
    heatmapWidget: 'crypto-coins-heatmap',
    heatmapDataSource: null,
    marketData: [
      { description: 'Bitcoin', proName: 'BINANCE:BTCUSDT' },
      { description: 'Ethereum', proName: 'BINANCE:ETHUSDT' },
      { description: 'Tether', proName: 'BINANCE:USDTUSD' },
      { description: 'BNB', proName: 'BINANCE:BNBUSDT' },
      { description: 'Solana', proName: 'BINANCE:SOLUSDT' },
      { description: 'XRP', proName: 'BINANCE:XRPUSDT' },
      { description: 'Cardano', proName: 'BINANCE:ADAUSDT' },
      { description: 'Dogecoin', proName: 'BINANCE:DOGEUSDT' },
      { description: 'Polkadot', proName: 'BINANCE:DOTUSDT' },
      { description: 'Polygon', proName: 'BINANCE:MATICUSDT' },
      { description: 'Litecoin', proName: 'BINANCE:LTCUSDT' },
      { description: 'Avalanche', proName: 'BINANCE:AVAXUSDT' },
      { description: 'Chainlink', proName: 'BINANCE:LINKUSDT' },
      { description: 'Uniswap', proName: 'BINANCE:UNIUSDT' },
      { description: 'Bitcoin Cash', proName: 'BINANCE:BCHUSDT' },
      { description: 'Stellar', proName: 'BINANCE:XLMUSDT' },
      { description: 'Cosmos', proName: 'BINANCE:ATOMUSDT' },
      { description: 'Algorand', proName: 'BINANCE:ALGOUSDT' },
      { description: 'VeChain', proName: 'BINANCE:VETUSDT' },
      { description: 'Filecoin', proName: 'BINANCE:FILUSDT' },
      { description: 'TRON', proName: 'BINANCE:TRXUSDT' },
      { description: 'Ethereum Classic', proName: 'BINANCE:ETCUSDT' },
      { description: 'Monero', proName: 'BINANCE:XMRUSDT' },
      { description: 'Hedera', proName: 'BINANCE:HBARUSDT' },
    ],
    currencies: ['USD', 'EUR'],
    advancedChart: 'BINANCE:BTCUSDT',
  },
  etf: {
    label: 'ETF',
    marketOverview: [
      {
        title: 'Equity ETFs',
        symbols: [
          { s: 'AMEX:SPY', d: 'SPDR S&P 500' },
          { s: 'NASDAQ:QQQ', d: 'Invesco QQQ Trust' },
          { s: 'AMEX:IWM', d: 'iShares Russell 2000' },
          { s: 'AMEX:DIA', d: 'SPDR Dow Jones' },
          { s: 'AMEX:VTI', d: 'Vanguard Total Stock' },
          { s: 'NASDAQ:VOO', d: 'Vanguard S&P 500' },
        ],
      },
      {
        title: 'Sector ETFs',
        symbols: [
          { s: 'AMEX:XLF', d: 'Financial Select' },
          { s: 'AMEX:XLK', d: 'Technology Select' },
          { s: 'AMEX:XLE', d: 'Energy Select' },
          { s: 'AMEX:XLV', d: 'Health Care Select' },
          { s: 'AMEX:XLI', d: 'Industrial Select' },
          { s: 'AMEX:XLP', d: 'Consumer Staples' },
        ],
      },
    ],
    heatmapWidget: 'etf-heatmap',
    heatmapDataSource: null,
    marketData: [
      { description: 'SPDR S&P 500 ETF', proName: 'AMEX:SPY' },
      { description: 'Invesco QQQ Trust', proName: 'NASDAQ:QQQ' },
      { description: 'iShares Russell 2000', proName: 'AMEX:IWM' },
      { description: 'SPDR Dow Jones Industrial', proName: 'AMEX:DIA' },
      { description: 'Vanguard Total Stock Market', proName: 'AMEX:VTI' },
      { description: 'Vanguard S&P 500', proName: 'NASDAQ:VOO' },
      { description: 'iShares MSCI EAFE', proName: 'NASDAQ:EFA' },
      { description: 'iShares MSCI Emerging Markets', proName: 'AMEX:EEM' },
      { description: 'Financial Select Sector', proName: 'AMEX:XLF' },
      { description: 'Technology Select Sector', proName: 'AMEX:XLK' },
      { description: 'Energy Select Sector', proName: 'AMEX:XLE' },
      { description: 'Health Care Select Sector', proName: 'AMEX:XLV' },
      { description: 'Consumer Discretionary Select', proName: 'AMEX:XLY' },
      { description: 'Industrial Select Sector', proName: 'AMEX:XLI' },
      { description: 'Consumer Staples Select', proName: 'AMEX:XLP' },
      { description: 'Utilities Select Sector', proName: 'AMEX:XLU' },
      { description: 'Real Estate Select Sector', proName: 'AMEX:XLRE' },
      { description: 'Materials Select Sector', proName: 'AMEX:XLB' },
      { description: 'Communication Services Select', proName: 'AMEX:XLC' },
      { description: 'iShares Core U.S. Aggregate Bond', proName: 'NASDAQ:AGG' },
      { description: 'iShares 20+ Year Treasury Bond', proName: 'NASDAQ:TLT' },
      { description: 'SPDR Gold Shares', proName: 'AMEX:GLD' },
      { description: 'iShares Silver Trust', proName: 'AMEX:SLV' },
      { description: 'United States Oil Fund', proName: 'AMEX:USO' },
    ],
    currencies: ['USD', 'EUR', 'GBP', 'JPY'],
    advancedChart: 'AMEX:SPY',
  },
};

export type MarketSector = keyof typeof SECTOR_CONFIGS;

