import * as T from 'three';import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';import {ITEMS} from './catalog.js';
export function powerupModel(kind){const g=new T.Group(),color=ITEMS[kind].color,metal=new T.MeshStandardMaterial({color:0x203346,metalness:.7,roughness:.26}),silver=new T.MeshStandardMaterial({color:0xb9d4e0,metalness:.62,roughness:.25}),glow=new T.MeshStandardMaterial({color,emissive:color,emissiveIntensity:1.35,roughness:.2});
 const add=(geo,mat,x=0,y=0,z=0)=>{const m=new T.Mesh(geo,mat);m.position.set(x,y,z);g.add(m);return m;};
 const ring=(r,y=0,mat=glow)=>{const m=add(new T.TorusGeometry(r,.07,10,40),mat,0,y);m.rotation.x=Math.PI/2;return m;};
 if(kind==='energy'){add(new T.CylinderGeometry(.55,.55,1.8,24),metal);add(new T.CylinderGeometry(.39,.39,1.95,24),glow);for(const y of [-.95,0,.95])ring(.62,y,silver);for(let i=0;i<4;i++){const a=i*Math.PI/2;add(new T.BoxGeometry(.12,1.55,.12),silver,Math.sin(a)*.56,0,Math.cos(a)*.56);}}
 if(kind==='repair'){add(new RoundedBoxGeometry(1.6,1.3,.65,3,.15),metal);add(new T.BoxGeometry(.32,.95,.15),glow,0,0,.4);add(new T.BoxGeometry(.98,.3,.15),glow,0,0,.4);for(const x of [-.75,.75])add(new T.BoxGeometry(.15,1.45,.8),silver,x);}
 if(kind==='shield'){add(new T.SphereGeometry(.85,32,24),glow);const shell=add(new T.IcosahedronGeometry(1.18,2),new T.MeshBasicMaterial({color,wireframe:true,transparent:true,opacity:.65}));shell.rotation.z=.4;ring(1.28,-.7,silver);}
 if(kind==='overdrive'){add(new T.CylinderGeometry(.55,.55,1,24),glow);for(let i=0;i<8;i++){const a=i*Math.PI/4,m=add(new T.BoxGeometry(.18,1.1,.75),silver,Math.sin(a)*.7,0,Math.cos(a)*.7);m.rotation.y=a+.45;}ring(1.05,.6);ring(1.05,-.6);}
 if(kind==='missile'){for(const x of [-.4,.4]){add(new T.CylinderGeometry(.22,.3,1.4,16),silver,x);add(new T.ConeGeometry(.23,.6,16),glow,x,1);add(new T.BoxGeometry(.75,.3,.12),metal,x,-.5);add(new T.CylinderGeometry(.2,.2,.18,16),glow,x,-.8);}}
 if(kind==='emp'){add(new T.SphereGeometry(.4,20,14),glow);for(let i=0;i<3;i++){const m=add(new T.TorusGeometry(.8+i*.16,.065,10,40),i===1?silver:glow);m.rotation.set(i*.8,i*1.3,i*.4);}}
 if(kind==='mine'){add(new T.CylinderGeometry(.75,.9,.5,32),metal);add(new T.SphereGeometry(.37,16,12),glow,0,.38);for(let i=0;i<6;i++){const a=i*Math.PI/3,m=add(new T.ConeGeometry(.15,.6,8),silver,Math.sin(a)*.9,0,Math.cos(a)*.9);m.rotation.z=Math.PI/2;m.rotation.y=a;}ring(.73,-.26);}
 if(kind==='counter'){for(let i=-1;i<=1;i++){const m=add(new T.CylinderGeometry(.2,.2,1.3,12),silver,i*.5,i===0?.25:0);m.rotation.z=-i*.25;add(new T.SphereGeometry(.23,12,8),glow,i*.5,.85+(i===0?.25:0));}ring(1.05,-.6);}
 // Open mechanical pickup cradle with independent rotating energy hoops.
 const accents=[];for(const y of [-1.35,1.35]){const r=ring(1.48,y,silver);accents.push(r);ring(1.36,y+.06,glow);}
 for(let i=0;i<4;i++){const a=i*Math.PI/2,x=Math.cos(a)*1.4,z=Math.sin(a)*1.4;add(new RoundedBoxGeometry(.14,2.55,.2,2,.035),metal,x,0,z);add(new T.BoxGeometry(.07,.7,.22),glow,x,.3,z);}
 const projection=add(new T.CylinderGeometry(1.2,.4,1.25,32,1,true),new T.MeshBasicMaterial({color,transparent:true,opacity:.10,blending:T.AdditiveBlending,depthWrite:false,side:T.DoubleSide}),0,-2);
 add(new T.CylinderGeometry(1.15,1.45,.28,48),metal,0,-1.45);for(let i=0;i<12;i++){const a=i*Math.PI/6;const m=add(new T.BoxGeometry(.16,.07,.35),silver,Math.cos(a)*1.28,-1.29,Math.sin(a)*1.28);m.rotation.y=-a;}
 const halo=ring(1.75,-1.6,new T.MeshBasicMaterial({color,transparent:true,opacity:.55,blending:T.AdditiveBlending,depthWrite:false}));accents.push(halo);g.userData.halo=halo;/* CHARTVOLT PATCH (28 Sep 2026): a light beam so a capsule reads from a distance. */g.userData.beam=add(new T.CylinderGeometry(.34,.7,8,20,1,true),new T.MeshBasicMaterial({color,transparent:true,opacity:.16,blending:T.AdditiveBlending,depthWrite:false,side:T.DoubleSide}),0,3.2);g.userData.accents=accents;return g;}
