import {buildRacingGuide,updateRacingGuide} from './racing-guide.js';
import {ShipExplosions} from './ship-explosion.js';
import {updateShadowFocus} from './shadow-focus.js';
import {updateMotorsportLights} from './motorsport-kit.js';
import {updateSpectators} from './spectators.js';
import {updateReferenceWorld} from './reference-world.js';
import {buildSkillGates,updateSkillGates} from './skill-gates.js';
import {powerupLabel,createSlickDecal,setCloaked} from './power-visuals.js';
import {updateSkyDetail} from './atmosphere-detail.js';
import {updateVolcanicFX} from './volcanic-fx.js';
import {buildTunnel,updateTunnelLighting} from './tunnel.js';
import {updateLivingWorld} from './living-world.js';
import {updateTrackLife} from './track-life.js';
import * as T from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {FXAAShader} from 'three/addons/shaders/FXAAShader.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {hoverClearance} from './hover.js';
import {createMissile,createPlasmaBolt,createTurret} from './weapons.js';
import {HALF_WIDTH} from './track.js';
import {road} from './road-width.js';
import {gridSlot,GRID_SLOTS} from './start-grid.js';
import {powerupModel} from './powerups.js';
import sparkTexture from '../assets/runtime/spark_01.webp';
import {createShip} from './ships.js';
import {SHIPS,ITEMS} from './catalog.js';
import {setupEnvironment,buildEnvironmentProps,createSentinel} from './environment.js';
export {SHIPS} from './catalog.js';

const UP=new T.Vector3(0,1,0);
const noiseGLSL=`float hash(vec3 p){p=fract(p*.3183099+vec3(.1,.2,.3));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm(vec3 p){float f=0.,a=.5;for(int i=0;i<5;i++){f+=a*noise(p);p=p*2.04+vec3(3.4,7.1,2.8);a*=.5;}return f;}`;
export class RaceScene{
  constructor(canvas,track){
    this.track=track;this.content=track.content;this.scene=new T.Scene();this.scene.fog=new T.FogExp2(0x18243e,.00037);
    this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer:coarse)').matches?1.25:1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.16;/* CHARTVOLT PATCH (28 Sep 2026): brighter scene, owner asked for it */this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;
    this.camera=new T.PerspectiveCamera(68,1,.2,9000);this.frame=track.frame(0);this.behind=track.frame(0);this.ahead=track.frame(0);this.pos=new T.Vector3();this.target=new T.Vector3();this.desired=new T.Vector3();this.camUp=new T.Vector3();this.basis=new T.Matrix4();this.q=new T.Quaternion();this.bankQ=new T.Quaternion();this.localZ=new T.Vector3(0,0,1);this.forwardNegative=new T.Vector3();this.cameraSet=false;this.reduced=false;
    this.materials={road:new T.MeshPhysicalMaterial({color:0x202d40,roughness:.69,metalness:.25}),side:new T.MeshStandardMaterial({color:0x111b2b,roughness:.52,metalness:.6}),stripe:new T.MeshStandardMaterial({color:0xd9ecb0,roughness:.8}),white:new T.MeshBasicMaterial({color:0xa5bace}),cyan:new T.MeshBasicMaterial({color:new T.Color(0x5fe6ee).multiplyScalar(2.2)}),pink:new T.MeshBasicMaterial({color:new T.Color(0xed53b8).multiplyScalar(2.1)})};
    this.materials.cyan.color.setHex(track.definition.color).multiplyScalar(1.6);this.materials.pink.color.setHex(track.definition.accent).multiplyScalar(1.6);
    setupEnvironment(this);this.buildRoad();this.buildWorld();this.buildDetails();this.ship=createShip(0);this.scene.add(this.ship);this.shipIndex=0;this.remoteShips=new Map();this.visualTime=0;this.explosions=new ShipExplosions(this.scene);
    this.buildTheme();buildEnvironmentProps(this);buildSkillGates(this);buildRacingGuide(this);this.localLights=Array.from({length:8},()=>{const light=new T.PointLight(0x5cdeff,0,28,2);this.scene.add(light);return light;});this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new T.Vector2(960,540),.38,.38,1.35);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());this.fxaa=new ShaderPass(FXAAShader);this.composer.addPass(this.fxaa);this.resize();
  }
  buildSky(){
    const sky=new T.Mesh(new T.SphereGeometry(6000,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,vertexShader:'varying vec3 vDir;void main(){vDir=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 vDir;${noiseGLSL}
void main(){vec3 d=normalize(vDir);vec3 p=d*3.5;float cloud=fbm(p*2.+fbm(p)*1.7);float band=exp(-pow((d.y+.02+sin(d.x*3.)*.18)*3.2,2.));vec3 base=vec3(.001,.004,.013);vec3 gas=mix(vec3(.003,.035,.07),vec3(.065,.009,.1),smoothstep(.35,.7,fbm(p*.8+15.)));base+=gas*pow(cloud,2.)*band;gl_FragColor=vec4(base,1.);}`}));sky.renderOrder=-10;this.sky=sky;this.scene.add(sky);
    const starGeo=new T.BufferGeometry(),p=[];let seed=12345;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<1700;i++){const a=rnd()*Math.PI*2,y=rnd()*2-1,r=Math.sqrt(1-y*y);p.push(Math.cos(a)*r*4500,y*4500,Math.sin(a)*r*4500);}starGeo.setAttribute('position',new T.Float32BufferAttribute(p,3));this.scene.add(new T.Points(starGeo,new T.PointsMaterial({color:0xcbdcff,size:2.5,sizeAttenuation:true,transparent:true,opacity:.8,depthWrite:false})));
  }
  strip(offset,width,height,material,start=0,end=this.track.length,steps=1400){
    const verts=[],uv=[],indices=[],f=this.track.frame(start),v=new T.Vector3();for(let i=0;i<=steps;i++){const d=start+(end-start)*i/steps;this.track.frame(d,f);for(const side of [-1,1]){v.copy(f.p).addScaledVector(f.right,offset+side*width/2).addScaledVector(f.up,height);verts.push(v.x,v.y,v.z);uv.push(side<0?0:1,d/20);}if(i<steps){const j=i*2;indices.push(j,j+1,j+2,j+1,j+3,j+2);}}
    const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();const mesh=new T.Mesh(g,material);this.scene.add(mesh);return mesh;
  }
  buildRoad(){
    this.roadMesh=this.strip(0,HALF_WIDTH*2,0,this.materials.road);this.roadMesh.receiveShadow=true;this.strip(0,HALF_WIDTH*2+2,-.65,this.materials.side);
    for(const sign of [-1,1]){this.strip(sign*(HALF_WIDTH-.4),.22,.07,sign<0?this.materials.pink:this.materials.cyan);this.strip(sign*(HALF_WIDTH+.35),.6,.3,this.materials.side);this.strip(sign*(HALF_WIDTH+.35),.18,.66,sign<0?this.materials.pink:this.materials.cyan);}
    const marks=[],curbs=[];for(let d=0;d<this.track.length;d+=12){for(const lane of [-5.3,5.3])marks.push(this.patchGeometry(d,d+4,lane,.13,.025));for(const side of [-1,1])curbs.push(this.patchGeometry(d,d+6,side*14.85,.8,.028));}
    this.merge(marks,this.materials.white);this.merge(curbs,this.materials.stripe);
    // Start/finish checkerboard across the road, with a distinct overhead arch.
    const tiles=[];for(let row=0;row<4;row++)for(let x=0;x<HALF_WIDTH;x++)if((row+x)%2===0)tiles.push(this.patchGeometry(row*1.6,row*1.6+1.6,-HALF_WIDTH+1+x*2,2,.04));/* CHARTVOLT PATCH (28 Sep 2026): painted F1 grid boxes, from the same gridSlot() the server places ships with. */for(let i=0;i<GRID_SLOTS;i++){const s=gridSlot(i);tiles.push(this.patchGeometry(s.distance+2.9,s.distance+3.25,s.lateral,4.4,.04));for(const e of [-2.05,2.05])tiles.push(this.patchGeometry(s.distance-.4,s.distance+3.25,s.lateral+e,.3,.04));}this.merge(tiles,new T.MeshBasicMaterial({color:0xeaf6ff}));
    this.pickups=[];for(let i=0;i<this.content.pickups.length;i++){const p=this.content.pickups[i],f=this.track.frame(p.distance),mesh=powerupModel(p.kind);mesh.position.copy(f.p).addScaledVector(f.right,p.lane).addScaledVector(f.up,2.4);mesh.userData.base=mesh.position.clone();mesh.userData.up=f.up.clone();this.pickups.push(mesh);this.scene.add(mesh);}
  }
  patchGeometry(a,b,x,width,height){const verts=[],uv=[],indices=[],steps=Math.max(1,Math.ceil((b-a)*2));for(let i=0;i<=steps;i++){const d=a+(b-a)*i/steps,f=this.track.frame(d);for(const side of [-1,1]){const p=f.p.clone().addScaledVector(f.right,x+side*width/2).addScaledVector(f.up,height+.065);verts.push(p.x,p.y,p.z);uv.push(side<0?0:1,d/20);}if(i<steps){const j=i*2;indices.push(j,j+1,j+2,j+1,j+3,j+2);}}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(verts,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.setIndex(indices);geo.computeVertexNormals();return geo;}
  beamGeometry(a,b,r){const d=new T.Vector3().subVectors(b,a),g=new T.CylinderGeometry(r,r,d.length(),6);g.applyQuaternion(new T.Quaternion().setFromUnitVectors(UP,d.normalize()));g.translate((a.x+b.x)/2,(a.y+b.y)/2,(a.z+b.z)/2);return g;}
  merge(geos,mat){if(!geos.length)return;const g=mergeGeometries(geos,false);for(const x of geos)x.dispose();const m=new T.Mesh(g,mat);this.scene.add(m);return m;}
  buildWorld(){
    this.orbital=new T.Group();if(!this.environment.planet)return;
    const planet=new T.Mesh(new T.SphereGeometry(380,64,32),new T.ShaderMaterial({vertexShader:'varying vec3 vP;varying vec3 vN;void main(){vP=position;vN=normal;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 vP;varying vec3 vN;${noiseGLSL}void main(){float n=.5+.5*sin(vP.y*.055+fbm(normalize(vP)*5.)*4.);float light=.15+.85*max(0.,dot(normalize(vN),normalize(vec3(-.7,.6,1.))));vec3 col=mix(vec3(.016,.06,.13),vec3(.25,.43,.6),smoothstep(.3,.75,n));col+=vec3(.03,.07,.11)*pow(n,8.);gl_FragColor=vec4(col*light,1.);}`}));planet.position.set(1050,780,-1950);this.scene.add(planet);
    const orbit=new T.Mesh(new T.TorusGeometry(520,2.6,8,160),new T.MeshBasicMaterial({color:0xcf9aaa,transparent:true,opacity:.38}));orbit.position.copy(planet.position);orbit.rotation.set(.55,.8,.1);this.scene.add(orbit);
    const f=this.track.frame(this.track.length*.2),landmark=new T.Group();landmark.position.copy(f.p).addScaledVector(f.right,-145).addScaledVector(f.up,90);landmark.lookAt(f.p);const black=new T.MeshStandardMaterial({color:0x22243d,metalness:.6,roughness:.4});for(let i=0;i<4;i++){const m=new T.Mesh(new T.TorusGeometry(36+i*10,i===1?1.3:.35,8,96),i%2?this.materials.pink:this.materials.cyan);landmark.add(m);}for(let i=0;i<24;i++){const spoke=new T.Mesh(new T.BoxGeometry(1,16,2),black);const a=i*Math.PI/12;spoke.position.set(Math.cos(a)*54,Math.sin(a)*54,0);spoke.rotation.z=a-Math.PI/2;landmark.add(spoke);}this.scene.add(landmark);this.orbital=landmark;

  }
  buildDetails(){
    const seams=[],armor=[],lights=[];
    for(let d=18;d<this.track.length;d+=24){seams.push(this.patchGeometry(d,d+.09,0,road(29),.035));for(const side of [-1,1]){const f=this.track.frame(d),p=f.p.clone().addScaledVector(f.right,side*(HALF_WIDTH+1.1)).addScaledVector(f.up,.9),geo=new T.BoxGeometry(1.25,1.2,6);this.basis.makeBasis(f.right,f.up,f.forward);geo.applyMatrix4(this.basis);geo.translate(p.x,p.y,p.z);armor.push(geo);lights.push(this.patchGeometry(d,d+3.8,side*(HALF_WIDTH-.1),.35,.72));}}
    this.merge(seams,new T.MeshBasicMaterial({color:0x080f1c}));this.merge(armor,this.materials.side);this.merge(lights,this.materials.cyan);
    this.hazards=[];for(let i=0;i<this.content.hazards.length;i++){const h=this.content.hazards[i],f=this.track.frame(h.distance),group=new T.Group(),core=createTurret();group.add(core);const ring=new T.Mesh(new T.TorusGeometry(2.2,.06,8,32),new T.MeshBasicMaterial({color:0xff5673}));ring.rotation.x=Math.PI/2;ring.position.y=.16;group.add(ring);group.position.copy(f.p).addScaledVector(f.right,h.lane).addScaledVector(f.up,h.height||0);this.basis.makeBasis(f.right,f.up,f.forward.clone().negate());group.quaternion.setFromRotationMatrix(this.basis);group.userData.core=core;const top=group.position.clone(),height=top.y+105;const pillar=new T.Mesh(new T.CylinderGeometry(1.6,2.6,height,16),this.materials.side);pillar.position.set(top.x,-105+height/2,top.z);pillar.castShadow=true;this.scene.add(pillar);const pad=new T.Mesh(new T.CylinderGeometry(4,4.6,.8,32),this.materials.side);pad.position.copy(top).addScaledVector(f.up,-.5);this.scene.add(pad);this.scene.add(group);this.hazards.push(group);}
    this.missiles=Array.from({length:4},()=>{const m=createMissile();m.visible=false;this.scene.add(m);return m;});
    this.effectRings=Array.from({length:8},()=>{const m=new T.Mesh(new T.TorusGeometry(1,.06,8,48),new T.MeshBasicMaterial({color:0x84eeff,transparent:true,opacity:0,blending:T.AdditiveBlending,depthWrite:false}));m.rotation.x=Math.PI/2;m.userData.life=0;m.visible=false;this.scene.add(m);return m;});this.effectCursor=0;this.particles=[];const positions=new Float32Array(480*3);this.particleGeo=new T.BufferGeometry();this.particleGeo.setAttribute('position',new T.BufferAttribute(positions,3));this.particlePoints=new T.Points(this.particleGeo,new T.PointsMaterial({color:0xffbe73,size:.35,transparent:true,opacity:.8,blending:T.AdditiveBlending,depthWrite:false}));this.scene.add(this.particlePoints);this.particleGeo.setDrawRange(0,0);
    this.particlePoints.material.map=new T.TextureLoader().load(sparkTexture);
    this.podium=new T.Group();const pf=this.track.frame(0);this.podium.position.copy(pf.p).addScaledVector(pf.up,.09);this.podium.quaternion.setFromUnitVectors(UP,pf.up);for(const r of [6.8,7.1,8.8]){const m=new T.Mesh(new T.TorusGeometry(r,.045,8,96),this.materials.cyan);m.rotation.x=Math.PI/2;this.podium.add(m);}this.scene.add(this.podium);
    /* CHARTVOLT PATCH (28 Sep 2026): one shared, readable name tag per capsule kind (power-visuals.js). */for(let i=0;i<this.pickups.length;i++)this.pickups[i].add(powerupLabel(this.content.pickups[i].kind));
  }
  effect(e,s){if(e.type==='pickup'){this.pickupBurst(this.ship.position.clone(),ITEMS[e.kind]?.color??0x7af0ff);return;}if(e.type==='ship-destroyed'){const f=this.track.frame(e.distance??s.distance),p=f.p.clone().addScaledVector(f.right,e.lane??s.lateral).addScaledVector(f.up,1.7);this.explosions.burst(p,f.up,f.right);this.ship.visible=false;return;}if(!['impact','destroy','use','pickup','respawn','skill'].includes(e.type))return;const f=this.track.frame(e.key?this.content.hazards[Number(e.key.split(':')[1])].distance:s.distance);const p=e.key?f.p.clone().addScaledVector(f.right,this.content.hazards[Number(e.key.split(':')[1])].lane).addScaledVector(f.up,this.content.hazards[Number(e.key.split(':')[1])].height||0):this.ship.position;const ring=this.effectRings[this.effectCursor++%this.effectRings.length];ring.position.copy(p);ring.material.color.setHex(e.kind&&ITEMS[e.kind]?ITEMS[e.kind].color:e.type==='destroy'?0xff975b:0x7af0ff);ring.userData.life=.65;ring.visible=true;ring.scale.setScalar(1);const count=e.type==='destroy'?65:24;for(let i=0;i<count;i++){if(this.particles.length>=480)this.particles.shift();const a=i*2.399;this.particles.push({p:p.clone(),v:new T.Vector3(Math.cos(a)*8,3+(i%5)*1.5,Math.sin(a)*8),life:.4+(i%7)*.12});}}
  updateDetails(s,dt){this.podium.visible=s.state==='hangar';this.hazards.forEach((h,i)=>{h.visible=!s.destroyed.has(`${s.lap}:${i}`);h.userData.core.userData.head.lookAt(this.ship.position);h.userData.core.userData.head.rotateY(Math.PI);const key=`${s.lap}:${i}`;if(s.fired.has(key)&&h.userData.firedKey!==key){h.userData.firedKey=key;h.userData.flashUntil=this.visualTime+.18;}h.userData.core.userData.flash.visible=this.visualTime<(h.userData.flashUntil||0);h.userData.core.position.y=.08;});this.missiles.forEach((m,i)=>{const p=s.projectiles[i];m.visible=!!p;if(p){const f=this.track.frame(p.distance);m.position.copy(f.p).addScaledVector(f.right,p.lane).addScaledVector(f.up,p.height||1.6);const tf=this.track.frame(p.targetDistance),target=tf.p.clone().addScaledVector(tf.right,p.targetLane).addScaledVector(tf.up,p.targetHeight||1.6);m.quaternion.setFromUnitVectors(new T.Vector3(0,0,-1),target.sub(m.position).normalize());}});if(s.state==='paused')dt=0;for(const r of this.effectRings){r.userData.life=Math.max(0,r.userData.life-dt);r.visible=r.userData.life>0;r.scale.setScalar(1+(1-r.userData.life/.65)*7);r.material.opacity=r.userData.life/.65;}for(const p of this.particles){p.life-=dt;p.p.addScaledVector(p.v,dt);p.v.y-=8*dt;}this.particles=this.particles.filter(p=>p.life>0);const attr=this.particleGeo.attributes.position;this.particles.forEach((p,i)=>attr.setXYZ(i,p.p.x,p.p.y,p.p.z));attr.needsUpdate=true;this.particleGeo.setDrawRange(0,this.particles.length);}
  buildTheme(){
    const theme=this.track.definition.theme,accent=this.track.definition.accent;
    if(this.environment.tunnel)buildTunnel(this);
    this.threatMeshes=Array.from({length:3},()=>{const m=createPlasmaBolt();m.visible=false;this.scene.add(m);return m;});
    this.mineMeshes=Array.from({length:3},()=>{const m=powerupModel('mine');m.scale.setScalar(.65);m.visible=false;this.scene.add(m);return m;});
  }
  chooseShip(index){if(index===this.shipIndex)return;this.scene.remove(this.ship);this.disposeTree(this.ship);this.ship=createShip(index);this.shipIndex=index;this.scene.add(this.ship);}
  update(s,dt,hangar=false){
    const distance=s.distance;this.track.frame(distance,this.frame);for(const cell of this.detailCells||[])cell.visible=cell.userData.center.distanceToSquared(this.frame.p)<(350+(cell.userData.detailRadius||0))**2;for(const cell of this.scanCells||[])cell.visible=cell.userData.center.distanceToSquared(this.frame.p)<((this.graphicsQuality?.textures==='low'?220:550)+cell.userData.radius)**2;const f=this.frame;this.ship.position.copy(f.p).addScaledVector(f.right,s.lateral).addScaledVector(f.up,(this.ship.userData.hoverHeight||1.12)+(this.reduced?0:Math.sin(s.time*8)*.07));this.forwardNegative.copy(f.forward).negate();this.basis.makeBasis(f.right,f.up,this.forwardNegative);this.q.setFromRotationMatrix(this.basis);this.bankQ.setFromAxisAngle(this.localZ,T.MathUtils.clamp(-s.lateralVelocity*.014,-.38,.38));this.ship.quaternion.copy(this.q);this.ship.rotateY(-s.heading);this.ship.quaternion.multiply(this.bankQ);const clearance=hoverClearance(this.track,distance,s.lateral,this.ship.quaternion,this.ship.userData.supportPoints,.65);this.ship.position.copy(f.p).addScaledVector(f.right,s.lateral).addScaledVector(f.up,clearance+(this.reduced?0:Math.sin(s.time*8)*.045));this.ship.userData.clearance=clearance;this.ship.userData.shield.visible=s.shield>0;this.ship.visible=!(s.respawnRemaining>0);if(s.state==='hangar')this.explosions.clear();
    if(this.cloudVolume)this.cloudVolume.material.uniforms.clock.value=this.visualTime;
    this.visualTime+=['paused','finished'].includes(s.state)?0:dt;const t=this.visualTime;if(this.referenceClock)this.referenceClock.value=t;updateLivingWorld(this,t);updateTrackLife(this,t);updateReferenceWorld(this,t);if(this.cityClock)this.cityClock.value=t;updateSkillGates(this,s,t);updateRacingGuide(this,s);updateVolcanicFX(this,t,s.step/60);if(this.biomeClock)this.biomeClock.value=t;for(const u of this.plantUniforms||[])u.value=t;for(const b of this.cloudDetails||[]){b.position.x=b.userData.origin.x+Math.sin(t*.018+b.userData.phase)*12;b.position.z=b.userData.origin.z+Math.sin(t*.012+b.userData.phase)*8;}
    setCloaked(this.ship,s.cloak>0);
    for(const flame of this.ship.userData.exhaust){if(flame.material.uniforms?.clock)flame.material.uniforms.clock.value=t;flame.visible=!hangar&&s.throttle&&s.speed>1;flame.scale.z=s.boosting?1.7:.6+s.speed/180;flame.position.z=flame.userData.base+(!flame.userData.anchored&&s.boosting?1.4:0);}
    for(let i=0;i<this.pickups.length;i++){const m=this.pickups[i];m.visible=this.sharedPickupHidden?!this.sharedPickupHidden.has(i):!s.used.has(`${s.lap}:${i}`);m.rotation.y=s.time*.65;if(m.userData.accents)for(let j=0;j<m.userData.accents.length;j++){m.userData.accents[j].rotation.y=this.visualTime*(j%2?-.8:.6);m.userData.accents[j].rotation.z=Math.sin(this.visualTime*1.4+j)*.13;}m.position.copy(m.userData.base).addScaledVector(m.userData.up,Math.sin(s.time*2+i)*.25);if(m.userData.beam)m.userData.beam.material.opacity=.12+.08*Math.sin(this.visualTime*3+i);}
    const nearest=this.content.pickups.map((p,i)=>({p,i,delta:Math.abs(((p.distance-distance+this.track.length*1.5)%this.track.length)-this.track.length*.5)})).filter(v=>this.pickups[v.i].visible).sort((a,b)=>a.delta-b.delta);
    for(let i=0;i<3;i++){const light=this.localLights[i],item=nearest[i];light.intensity=item&&item.delta<90?55:0;if(light.intensity){light.color.setHex(ITEMS[item.p.kind].color);light.position.copy(this.pickups[item.i].position);light.position.y-=.7;}}
    const engine=this.localLights[3];engine.position.copy(this.ship.position).addScaledVector(f.forward,-3).addScaledVector(f.up,-.35);engine.intensity=s.respawnRemaining>0?0:s.throttle?65:12;
    updateMotorsportLights(this);updateTunnelLighting(this,s);
    updateSpectators(this);
    this.updateDetails(s,dt);for(const [pool,objects] of [[this.threatMeshes,s.threats],[this.mineMeshes,s.mines]])pool.forEach((m,i)=>{const p=objects[i];m.visible=!!p;if(p){const f=this.track.frame(p.distance);m.position.copy(f.p).addScaledVector(f.right,p.lane).addScaledVector(f.up,p.height||1.4);if(p.startDistance!==undefined){const slope=new T.Vector3().copy(f.forward).negate().addScaledVector(f.right,(p.aimLane-p.startLane)/Math.max(1,p.startDistance-p.aimDistance)).addScaledVector(f.up,(1.4-p.startHeight)/Math.max(1,p.startDistance-p.aimDistance));m.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),slope.normalize());}else m.rotation.y=t;}});
    if(hangar){const orbit=t*.13;this.desired.copy(this.ship.position).addScaledVector(f.forward,-Math.cos(orbit)*14).addScaledVector(f.right,Math.sin(orbit)*11+5).addScaledVector(f.up,6);this.target.copy(this.ship.position).addScaledVector(f.right,-(this.camera.aspect>1.2?4:0));this.camUp.copy(f.up);}
    else {const portrait=this.camera.aspect<1;this.desired.copy(this.ship.position).addScaledVector(f.forward,-(portrait?29:s.boosting?28:24)).addScaledVector(f.up,portrait?10:8.2);this.track.frame(distance+34,this.ahead);this.target.copy(this.ahead.p).addScaledVector(this.ahead.right,s.lateral).lerp(this.ship.position,.32).addScaledVector(f.up,.2);this.camUp.copy(UP).lerp(f.up,this.reduced?0:.18).normalize();}
    const alpha=this.cameraSet&&this.camera.position.distanceTo(this.desired)<35?1-Math.exp(-dt*8):1;this.camera.position.lerp(this.desired,alpha);this.camera.up.lerp(this.camUp,alpha).normalize();this.camera.lookAt(this.target);this.applyShake(dt);const goal=hangar?55:s.boosting&&!this.reduced?76:68;this.camera.fov=T.MathUtils.lerp(this.camera.fov,goal,alpha);this.camera.updateProjectionMatrix();this.cameraSet=true;updateShadowFocus(this);this.sky.position.copy(this.camera.position);updateSkyDetail(this,t);this.orbital.rotation.z=s.time*.025;this.explosions.update(['paused','finished'].includes(s.state)?0:dt,this.camera,this.reduced);
  }
  render(){this.renderer.info.autoReset=false;this.renderer.info.reset();this.composer.render();}
  resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.composer.setPixelRatio(this.renderer.getPixelRatio());this.composer.setSize(w,h);this.fxaa.material.uniforms.resolution.value.set(1/(w*this.renderer.getPixelRatio()),1/(h*this.renderer.getPixelRatio()));this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
  // CHARTVOLT PATCH (28 Sep 2026): a visible burst when any racer collects a capsule - three rings in the item's colour and a spray of sparks.
  pickupBurst(p,color){for(const life of [.65,.52,.4]){const ring=this.effectRings[this.effectCursor++%this.effectRings.length];ring.position.copy(p);ring.material.color.setHex(color);ring.userData.life=life;ring.visible=true;}for(let i=0;i<36;i++){if(this.particles.length>=480)this.particles.shift();const a=i*2.399;this.particles.push({p:p.clone(),v:new T.Vector3(Math.cos(a)*6,6+(i%6)*1.8,Math.sin(a)*6),life:.55+(i%6)*.1});}}
  // CHARTVOLT PATCH (28 Sep 2026): a hull-to-hull bump - a white-hot ring and sparks thrown sideways at the contact point, sized by impact force.
  bumpBurst(e){if((e.age||0)>.4)return;const f=this.track.frame(e.distance),p=f.p.clone().addScaledVector(f.right,e.lane).addScaledVector(f.up,1.3),force=Math.min(1,(e.force||6)/30);const ring=this.effectRings[this.effectCursor++%this.effectRings.length];ring.position.copy(p);ring.material.color.setHex(0xffd9a8);ring.userData.life=.35+force*.3;ring.visible=true;ring.scale.setScalar(1);for(let i=0;i<14+Math.round(force*26);i++){if(this.particles.length>=480)this.particles.shift();const side=i%2?1:-1,a=i*2.399;this.particles.push({p:p.clone(),v:f.right.clone().multiplyScalar(side*(7+(i%4)*3)).addScaledVector(f.up,2+(i%5)*1.4).addScaledVector(f.forward,Math.cos(a)*4),life:.25+(i%5)*.07});}}
  // Reason: applied AFTER lookAt so it never moves where the camera is aimed, only jitters it; skipped under reduced motion.
  shakeBy(amount){if(this.reduced)return;this.shake=Math.min(1,(this.shake||0)+amount);}
  applyShake(dt){if(!this.shake)return;this.shake=Math.max(0,this.shake-dt*3.2);const k=this.shake*this.shake*.035,t=this.visualTime*55;this.camera.rotateX(Math.sin(t)*k);this.camera.rotateY(Math.cos(t*1.3)*k);this.camera.rotateZ(Math.sin(t*.7)*k*.6);}
  combatEffect(e){
    if(e.type==='bump'){this.bumpBurst(e);return;}
    if(e.type==='pickup'){const f=this.track.frame(e.distance),p=f.p.clone().addScaledVector(f.right,e.lane).addScaledVector(f.up,1.5);this.pickupBurst(p,ITEMS[e.kind]?.color??0x7af0ff);return;}
    if(e.type==='destroyed'||e.type==='destroy'){const f=this.track.frame(e.distance),p=f.p.clone().addScaledVector(f.right,e.lane).addScaledVector(f.up,e.height||1.7);this.explosions.burst(p,f.up,f.right,e.age||0,e.type==='destroyed'?1:.7);return;}if(e.type==='respawn'){const f=this.track.frame(e.distance),p=f.p.clone().addScaledVector(f.right,e.lane).addScaledVector(f.up,1);const ring=this.effectRings[this.effectCursor++%this.effectRings.length];ring.position.copy(p);ring.material.color.setHex(0x65eaff);ring.userData.life=.65;ring.visible=true;return;}
    if(!['hit','destroyed','pulse','blocked','intercept','detonate','shockwave','spin'].includes(e.type))return;
    const f=this.track.frame(e.distance),p=f.p.clone().addScaledVector(f.right,e.lane).addScaledVector(f.up,1.5);
    const ring=this.effectRings[this.effectCursor++%this.effectRings.length];ring.position.copy(p);ring.material.color.setHex(e.type==='blocked'?0x62cdff:e.type==='pulse'?0xb77dff:e.type==='shockwave'?0x4dfff0:e.type==='spin'?0xd8ff3d:0xff975b);if(e.type==='shockwave'){const outer=this.effectRings[this.effectCursor++%this.effectRings.length];outer.position.copy(p);outer.material.color.setHex(0x4dfff0);outer.userData.life=.45;outer.visible=true;}ring.userData.life=.65;ring.visible=true;ring.scale.setScalar(1);
    for(let i=0;i<(e.type==='destroyed'?65:20);i++){if(this.particles.length>=480)this.particles.shift();const a=i*2.399;this.particles.push({p:p.clone(),v:new T.Vector3(Math.cos(a)*9,3+(i%5)*1.6,Math.sin(a)*9),life:.5+(i%5)*.12});}
  }
  updatePlayerCombat(combat){
    if(!this.playerWeapons)this.playerWeapons=new Map();if(this.lastCombatSnapshot!==combat){this.lastCombatSnapshot=combat;this.lastCombatReceived=performance.now();}const extrapolate=Math.min(.1,(performance.now()-(this.lastCombatReceived||0))/1000);
    const objects=[...(combat?.missiles||[]).map(p=>({...p,type:'missile'})),...(combat?.mines||[]).map(p=>({...p,type:'mine'})),...(combat?.bolts||[]).map(p=>({...p,type:'blaster'})),...(combat?.slicks||[]).map(p=>({...p,type:'slick'}))],ids=new Set(objects.map(p=>p.id));
    for(const [id,m]of this.playerWeapons)if(!ids.has(id)){this.scene.remove(m);this.disposeTree(m);this.playerWeapons.delete(id);}
    for(const p of objects){let m=this.playerWeapons.get(p.id);if(!m){m=p.type==='slick'?createSlickDecal(3.2):p.type==='missile'?createMissile():p.type==='blaster'?createPlasmaBolt():powerupModel('mine');if(p.type==='mine')m.scale.setScalar(.6);if(p.type==='blaster')m.scale.setScalar(.65);this.scene.add(m);this.playerWeapons.set(p.id,m);}
      const f=this.track.frame(p.distance+(p.speed||0)*extrapolate);m.position.copy(f.p).addScaledVector(f.right,p.lane+(p.sideSpeed||0)*extrapolate).addScaledVector(f.up,p.type==='mine'?.65:p.type==='slick'?.1:1.6);m.quaternion.setFromUnitVectors(new T.Vector3(0,0,-1),f.forward.clone().addScaledVector(f.right,(p.sideSpeed||0)/Math.max(1,p.speed||240)).normalize());
    }
  }
  // CHARTVOLT PATCH: `lead` (seconds) draws each rival where it is now rather than where the last
  // snapshot saw it, using the same motion rule as the physics (distance += speed*cos(heading)*dt).
  updateOpponents(players,selfId,dt,lead=0){
    const ids=new Set(players.filter(p=>p.id!==selfId&&p.active&&!p.dnf).map(p=>p.id));
    for(const [id,entry]of this.remoteShips)if(!ids.has(id)){this.scene.remove(entry.mesh);entry.labelTexture.dispose();this.disposeTree(entry.mesh);this.remoteShips.delete(id);}
    for(const p of players){if(!ids.has(p.id))continue;let entry=this.remoteShips.get(p.id);
      if(!entry){const index=Math.max(0,SHIPS.findIndex(s=>s.id===p.shipId)),mesh=createShip(index),c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#041521dd';ctx.fillRect(0,0,512,96);ctx.strokeStyle='#79eaff';ctx.strokeRect(2,2,508,92);ctx.fillStyle='#e5f9ff';ctx.font='bold 30px Arial';ctx.textAlign='center';ctx.fillText(p.name,256,58,480);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const label=new T.Sprite(new T.SpriteMaterial({map:tex,transparent:true,depthWrite:false}));label.position.y=5;label.scale.set(10,1.875,1);mesh.add(label);this.scene.add(mesh);entry={mesh,label,labelTexture:tex,distance:p.distance,lateral:p.lateral,heading:p.heading};this.remoteShips.set(p.id,entry);}
      const step=Math.min(dt,.15),moving=p.connected&&p.finishTimeMs==null&&!(p.respawnRemaining>0),velocity=moving?p.speed*Math.cos(p.heading):0,target=p.distance+velocity*lead;
      // Reason: a respawn or rejoin is a real jump; gliding across it would fly the ship through the course.
      if(Math.abs(target-entry.distance)>40||Math.abs(p.lateral-entry.lateral)>10){entry.distance=target;entry.lateral=p.lateral;entry.heading=p.heading;}
      // Reason: advancing by the rival's own velocity before easing removes the fixed lag a plain ease leaves behind a moving target.
      const alpha=1-Math.exp(-step*14);entry.distance=T.MathUtils.lerp(entry.distance+velocity*step,target,alpha);entry.lateral=T.MathUtils.lerp(entry.lateral,p.lateral,alpha);entry.heading=T.MathUtils.lerp(entry.heading,p.heading,alpha);
      const f=this.track.frame(entry.distance),m=entry.mesh,basis=new T.Matrix4().makeBasis(f.right,f.up,f.forward.clone().negate());m.quaternion.setFromRotationMatrix(basis);m.rotateY(-entry.heading);const height=hoverClearance(this.track,entry.distance,entry.lateral,m.quaternion,m.userData.supportPoints,.65);m.position.copy(f.p).addScaledVector(f.right,entry.lateral).addScaledVector(f.up,height);m.userData.shield.visible=p.shield>0;setCloaked(m,Boolean(p.cloak));m.visible=(p.connected||p.finishTimeMs!=null)&&!(p.respawnRemaining>0);const range=m.position.distanceTo(this.camera.position),width=Math.min(9,Math.max(.5,range*.2));entry.label.scale.set(width,width*96/512,1);entry.label.visible=range>6;
    }
  }
  disposeTree(root){root.traverse(o=>{o.userData.liveryTexture?.dispose();o.customDepthMaterial?.dispose();o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});}
  dispose(){this.disposed=true;const textures=new Set();this.scene.traverse(o=>{for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[]){for(const key of ['map','normalMap','roughnessMap','emissiveMap','metalnessMap'])if(m[key])textures.add(m[key]);}});for(const t of textures)t.dispose();for(const t of this.environmentTextures||[])t.dispose();this.disposeTree(this.scene);this.cloudNoise?.dispose();this.environmentTarget?.dispose();this.composer.dispose();this.renderer.dispose();}
}
