import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/database/mongoose';
import PaymentProvider from '@/database/models/payment-provider.model';
import { requireAdminAuth } from '@/lib/admin/auth';
import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * POST /api/admin/payment-providers/regenerate-env
 * Clean up and regenerate the .env file payment providers section
 */
export async function POST() {
  try {
    await requireAdminAuth();
    await connectToDatabase();

    const envPath = path.join(process.cwd(), '.env');
    
    // Read existing .env content
    let existingContent = '';
    try {
      existingContent = await fs.readFile(envPath, 'utf-8');
    } catch (error) {
      return NextResponse.json(
        { error: '.env file not found' },
        { status: 404 }
      );
    }

    // Remove ALL occurrences of payment providers sections (to clean duplicates)
    let cleanedContent = existingContent;
    const startMarker = '# ============================================';
    const sectionHeader = '# PAYMENT PROVIDERS';
    
    // Keep removing payment provider sections until none are found
    let foundSection = true;
    while (foundSection) {
      const startIndex = cleanedContent.indexOf(startMarker + '\n' + sectionHeader);
      
      if (startIndex !== -1) {
        // Find the end marker
        const afterStart = startIndex + startMarker.length + sectionHeader.length + 2;
        const nextSectionIndex = cleanedContent.indexOf('\n' + startMarker, afterStart);
        
        if (nextSectionIndex !== -1) {
          // Remove from start marker to just before the next section
          cleanedContent = cleanedContent.slice(0, startIndex) + cleanedContent.slice(nextSectionIndex + 1);
        } else {
          // No next section found, remove from start marker to end of file
          cleanedContent = cleanedContent.slice(0, startIndex).trimEnd() + '\n';
        }
      } else {
        foundSection = false;
      }
    }

    // Get all providers that should be saved to .env
    const providers = await PaymentProvider.find({ saveToEnv: true });

    if (providers.length > 0) {
      // Build payment providers section
      const providerLines: string[] = [];
      providerLines.push('');
      providerLines.push('# ============================================');
      providerLines.push('# PAYMENT PROVIDERS');
      providerLines.push('# Auto-generated by Admin Panel');
      providerLines.push('# ============================================');

      for (const provider of providers) {
        providerLines.push('');
        providerLines.push(`# ${provider.displayName}`);
        
        for (const cred of provider.credentials) {
          const envKey = `${provider.slug.toUpperCase()}_${cred.key.toUpperCase()}`;
          providerLines.push(`${envKey}=${cred.value || ''}`);
        }

        if (provider.webhookUrl) {
          providerLines.push(`${provider.slug.toUpperCase()}_WEBHOOK_URL=${provider.webhookUrl}`);
        }
        
        providerLines.push(`${provider.slug.toUpperCase()}_TEST_MODE=${provider.testMode}`);
        providerLines.push(`${provider.slug.toUpperCase()}_ACTIVE=${provider.isActive}`);
      }

      // Append new payment providers section
      cleanedContent = cleanedContent.trimEnd() + '\n' + providerLines.join('\n') + '\n';
    }

    // Write cleaned content back to .env file
    await fs.writeFile(envPath, cleanedContent, 'utf-8');
    
    console.log('✅ Successfully regenerated .env file (removed duplicates)');

    return NextResponse.json({
      success: true,
      message: '.env file regenerated successfully. Duplicates removed.',
      providersCount: providers.length,
    });
  } catch (error: any) {
    if (error.message === 'Unauthorized') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    console.error('Regenerate .env error:', error);
    return NextResponse.json(
      { error: 'Failed to regenerate .env file' },
      { status: 500 }
    );
  }
}

