import test from 'node:test';import assert from 'node:assert/strict';
import {RaceRoom} from '../server/race-room.mjs';import {issueTicket,verifyTicket} from '../server/tickets.mjs';
import {serializeSimulation,restoreSimulation,standings} from '../src/multiplayer-state.js';
import {RaceSimulation} from '../src/simulation.js';import {SHIPS,shipMetrics,SHIP_TRADEOFFS} from '../src/catalog.js';
const spec={id:'race-a',trackId:'orbital',seed:123,players:[{id:'alice',name:'Alice'},{id:'bob',name:'Bob'}]};
const drive={steer:0,throttle:true,brake:false,boost:false,fire:false};
function started(){const r=new RaceRoom(spec,0);for(const p of spec.players){r.join(p.id,0);r.ready(p.id,true,0);}r.advance(5000);return r;}
test('each ship exposes accurate hull points, strengths and weaknesses',()=>{for(const s of SHIPS){assert.equal(shipMetrics(s).hullPoints,Math.round(s.armor*100));assert.equal(SHIP_TRADEOFFS[s.id].length,2);}const a=new RaceSimulation(1000),b=new RaceSimulation(1000);a.selectShip('comet');b.selectShip('bastion');a.damage(.5);b.damage(.5);assert.ok(a.hull<b.hull);assert.equal(shipMetrics(SHIPS.find(s=>s.id==='comet')).hullPoints,85);assert.equal(shipMetrics(SHIPS.find(s=>s.id==='bastion')).hullPoints,128);});
test('room requires valid registered roster and seeded fixed circuit',()=>{assert.throws(()=>new RaceRoom({...spec,players:[spec.players[0]]}));assert.throws(()=>new RaceRoom({...spec,players:[spec.players[0],spec.players[0]]}));assert.throws(()=>new RaceRoom({...spec,trackId:'custom'}));assert.throws(()=>new RaceRoom({...spec,seed:NaN}));const r=new RaceRoom(spec,0);assert.throws(()=>r.join('intruder',0));assert.throws(()=>r.start(0));});
test('two ready players share countdown and ship locks',()=>{const r=new RaceRoom(spec,0);r.join('alice',0);r.select('alice','comet');r.ready('alice',true,0);assert.equal(r.status,'lobby');assert.throws(()=>r.select('alice','bastion'));r.join('bob',0);r.ready('bob',true,0);assert.equal(r.startAt,5000);r.advance(4999);assert.equal(r.player('alice').sim.distance,0);r.advance(5017);assert.equal(r.status,'racing');assert.equal(r.player('alice').sim.shipId,'comet');assert.throws(()=>r.select('alice','pulse'));});
test('authoritative inputs ignore injected position, score and ship; reject duplicate/invalid input',()=>{const r=started();assert.equal(r.input('alice',{seq:1,input:drive,distance:1e9,shipId:'comet',time:0},5000),true);assert.equal(r.input('alice',{seq:1,input:drive},5001),false);assert.equal(r.input('alice',{seq:2,input:{...drive,steer:Infinity}},5001),false);for(let i=1;i<12;i++)r.advance(5000+i*17);assert.ok(r.player('alice').sim.distance>0);assert.ok(r.player('alice').sim.distance<10);assert.equal(r.player('alice').sim.shipId,'vanguard');assert.equal(r.player('bob').sim.distance,0);});
test('stale controls release and reconnect retains progress without identity duplication',()=>{const r=started();r.input('alice',{seq:1,input:drive},5000);r.advance(5100);r.advance(5400);assert.equal(r.player('alice').sim.throttle,false);const d=r.player('alice').sim.distance;r.disconnect('alice',5400);r.join('alice',5500);assert.equal(r.players.size,2);assert.equal(r.player('alice').sim.distance,d);assert.equal(r.player('alice').lastSeq,1);r.disconnect('alice',5500);r.advance(36001);assert.equal(r.player('alice').dnf,true);});
test('positions use validated checkpoint progress, finish penalties and shared tie ranks',()=>{const r=started(),a=r.player('alice'),b=r.player('bob');a.sim.distance=500;a.sim.checkpoints=1;b.sim.distance=800;b.sim.checkpoints=2;assert.equal(r.ranked()[0].id,'bob');a.finishTimeMs=110000;b.finishTimeMs=111000;assert.equal(r.ranked()[0].id,'alice');b.finishTimeMs=110000;assert.deepEqual(r.ranked().map(x=>x.position),[1,1]);b.dnf=true;assert.equal(r.ranked()[1].position,null);});
test('real wall-clock race deadline ends stalled race and finalizes DNF',()=>{const r=started();r.advance(306000);assert.equal(r.status,'finished');assert.ok(r.result().results.every(p=>p.dnf));assert.equal(r.result().final,true);});
test('full snapshot restores mutable gameplay state independently',()=>{const r=started(),a=r.player('alice').sim,b=new RaceSimulation(r.track.length,r.track.curvature);a.collect('shield');a.used.add('1:4');const data=serializeSimulation(a);restoreSimulation(b,data);assert.equal(b.item,'shield');assert.ok(b.used.has('1:4'));b.used.add('x');assert.equal(a.used.has('x'),false);assert.deepEqual(serializeSimulation(b),{...data,used:['1:4','x']});});
test('tickets validate signature, expiry, audience and race/player identity',()=>{const key='a'.repeat(40),claims={aud:'volt-velocity',raceId:'race-a',playerId:'alice',exp:100};const t=issueTicket(claims,key);assert.deepEqual(verifyTicket(t,key,1000),claims);assert.throws(()=>verifyTicket(t,'b'.repeat(40),1000));assert.throws(()=>verifyTicket(t,key,101000));assert.throws(()=>verifyTicket(t+'x',key,1000));assert.throws(()=>verifyTicket(issueTicket({...claims,aud:'other'},key),key,1000));});
