import test from 'node:test';import assert from 'node:assert/strict';import {RaceRoom} from '../server/race-room.mjs';
const drive={steer:0,throttle:false,brake:false,boost:false,fire:false};
function setup(){const r=new RaceRoom({id:'combat-test',trackId:'orbital',seed:123,players:[{id:'a',name:'Alpha'},{id:'b',name:'Bravo'}]},0);for(const p of r.players.values()){r.join(p.id,0);r.ready(p.id,true,0);}r.advance(5000);const a=r.player('a'),b=r.player('b');for(const p of [a,b]){p.sim.shield=0;p.sim.lateral=0;p.sim.content.hazards=[];}a.sim.distance=300;b.sim.distance=370;return{r,a,b};}
function steps(r,n){for(let i=0;i<n;i++){r.lastNow+=1000/60;r.step(r.lastNow);}}
test('homing missile really damages another player and respects armor',()=>{const {r,a,b}=setup();b.sim.shipId='comet';a.sim.item='missile';a.sim.useItem();assert.equal(r.combat.missiles.length,1);assert.equal(r.combat.missiles[0].target,'b');steps(r,30);assert.ok(b.sim.hull<1);assert.equal(a.sim.item,null);assert.equal(a.combat.hits,1);assert.equal(a.combat.damageDealt,32);assert.equal(r.combat.missiles.length,0);});
test('shield blocks a player missile; countermeasure intercepts and prevents locks',()=>{let {r,a,b}=setup();b.sim.shield=3;a.sim.item='missile';a.sim.useItem();steps(r,30);assert.equal(b.sim.hull,1);assert.ok(r.combat.events.some(e=>e.type==='blocked'));({r,a,b}=setup());a.sim.item='missile';a.sim.useItem();b.sim.item='counter';b.sim.useItem();assert.equal(r.combat.missiles.length,0);assert.equal(r.combat.target(a),undefined);});
test('mines are left behind, arm, ambush another racer and cannot hit their owner',()=>{const {r,a,b}=setup();a.sim.distance=500;b.sim.distance=480;a.sim.item='mine';a.sim.useItem();assert.equal(r.combat.mines[0].distance,492);steps(r,37);b.sim.distance=492;steps(r,1);assert.ok(b.sim.hull<1);assert.equal(a.sim.hull,1);assert.equal(r.combat.mines.length,0);});
test('EMP damages/slows nearby opponents and drains energy, but ignores distant ships',()=>{let {r,a,b}=setup();b.sim.distance=340;b.sim.speed=100;a.sim.item='emp';a.sim.useItem();assert.ok(b.sim.hull<1);assert.equal(b.sim.speed,55.00000000000001);assert.equal(b.sim.energy,.65);({r,a,b}=setup());b.sim.distance=500;a.sim.item='emp';a.sim.useItem();assert.equal(b.sim.hull,1);});
test('physical contact separates hulls and damages both, without pushing progress forward',()=>{const {r,a,b}=setup();b.sim.distance=a.sim.distance+2;a.sim.speed=100;b.sim.speed=50;const dA=a.sim.distance,dB=b.sim.distance;r.combat.step(1/60,new Map([['a',{distance:dA}],['b',{distance:dB}]]));assert.ok(Math.abs(a.sim.lateral-b.sim.lateral)>=3.4);assert.ok(a.sim.hull<1&&b.sim.hull<1);assert.equal(a.sim.distance,dA);assert.equal(b.sim.distance,dB);assert.equal(a.combat.collisions,1);});
test('combat uses physical course distance across the lap seam',()=>{const {r,a,b}=setup();a.sim.distance=r.track.length-40;b.sim.distance=r.track.length+25;a.sim.item='missile';a.sim.useItem();steps(r,30);assert.ok(b.sim.hull<1);});
test('destroyed opponents respawn with penalty and immunity; kill credited once',()=>{const {r,a,b}=setup();b.sim.hull=.1;const time=b.sim.time;r.combat.hit(a,b,.32,.65,'missile');assert.equal(b.sim.hull,0);assert.equal(b.sim.time,time);assert.equal(b.sim.respawnRemaining,3);assert.equal(b.sim.respawns,1);assert.equal(a.combat.kills,1);r.combat.hit(a,b,.32,.65,'missile');assert.equal(a.combat.kills,1);steps(r,180);assert.equal(b.sim.hull,1);assert.equal(b.sim.shield,3);assert.equal(b.sim.respawnRemaining,0);assert.equal(r.combat.events.filter(e=>e.type==='destroyed').length,1);assert.ok(r.combat.events.some(e=>e.type==='respawn'));});
test('shared pickups have one winner and seven-second respawn for all players',()=>{const {r,a,b}=setup();const pickup=r.track.content.pickups[0];pickup.kind='shield';a.sim.lateral=b.sim.lateral=pickup.lane;a.sim.distance=b.sim.distance=pickup.distance+1;const old=new Map([['a',{distance:pickup.distance-1}],['b',{distance:pickup.distance-2}]]);r.combat.sharedPickups([a,b],old);assert.equal(a.sim.item,'shield');assert.equal(b.sim.item,null);assert.ok(r.combat.snapshot('a').unavailablePickups.includes(0));r.raceElapsed+=7.1;r.combat.sharedPickups([b],old);assert.equal(b.sim.item,'shield');});
test('blaster consumes energy, damages a real opponent, and enforces cooldown',()=>{const {r,a,b}=setup();const energy=a.sim.energy;a.sim.useItem();assert.equal(r.combat.bolts.length,1);assert.equal(a.sim.energy,energy-.025);a.sim.useItem();assert.equal(r.combat.bolts.length,1);steps(r,20);assert.ok(b.sim.hull<1);assert.equal(a.combat.hits,1);});
test('finished racers cannot be targeted or harmed and forged fire cannot choose damage',()=>{const {r,a,b}=setup();b.sim.state='finished';b.finishTimeMs=1000;assert.equal(r.combat.target(a),undefined);r.combat.hit(a,b,1,.1,'missile');assert.equal(b.sim.hull,1);const accepted=r.input('a',{seq:1,input:{...drive,fire:true},weapon:'missile',damage:999,target:'b'},5000);assert.equal(accepted,true);assert.equal(a.sim.item,null);});
test('sixteen racers receive a reproducible separated starting grid',()=>{const players=Array.from({length:16},(_,i)=>({id:'p'+i,name:'Pilot '+i}));function room(roster){const r=new RaceRoom({id:'grid-test',trackId:'orbital',seed:42,players:roster},0);for(const p of roster){r.join(p.id,0);r.ready(p.id,true,0);}return r;}const a=room(players),b=room(players.slice().reverse());const positions=[...a.players.values()].map(p=>p.sim.distance+':'+p.sim.lateral);assert.equal(new Set(positions).size,16);for(const [id,p]of a.players){assert.equal(p.sim.distance,b.player(id).sim.distance);assert.equal(p.sim.lateral,b.player(id).sim.lateral);assert.ok(p.sim.shield>0);}});
