/**
 * Deterministic journey blueprint — one map per scope, milestones on the same
 * threshold ladder the badges use.
 *
 * Reason: journey content was generated by an AI prompt written when trading was
 * the only game, so a reset deleted every map and re-created either nothing or a
 * set of trading milestones. Nothing threw and nothing logged — the player was
 * simply shown an empty journey. The arithmetic here is fixed and testable, and
 * the AI is left to reword what this produces rather than to decide it.
 *
 * Two properties are load-bearing and each has a test:
 *
 *  - **The thresholds come from `badge-blueprint.ts`**, not from a second ladder
 *    in this file. A milestone asking for 50 wins beside a badge asking for 40
 *    is not a bug that throws; it is a journey that disagrees with the badge
 *    shelf, and only a reader comparing two files would ever notice.
 *  - **Every scope in the quota plan gets a map.** The failure this replaces is
 *    exactly a games-only player opening a journey that describes trading, so
 *    the map list is derived from the same plan the badges are, never from a
 *    hard-coded list of one.
 */

import {
  conditionsForScope,
  isBooleanCondition,
  thresholdFor,
  DESCENDING_TYPES,
  PERCENTAGE_TYPES,
} from "./badge-blueprint";
import { type BadgeConditionDef } from "./badge-condition-registry";
import {
  DEFAULT_BADGE_XP,
  deriveLadderBands,
  type BadgeQuotaPlan,
  type ScopeQuota,
} from "./gamification-economy";

export type MapTheme =
  | "pirate"
  | "space"
  | "medieval"
  | "cyber"
  | "ancient"
  | "volcanic"
  | "arctic"
  | "dragon"
  | "celestial"
  | "legendary";

export interface BlueprintZone {
  id: string;
  name: string;
  description: string;
  order: number;
  position: { x: number; y: number };
  color: string;
  icon: string;
  isUnlockable: boolean;
}

export interface BlueprintMilestone {
  id: string;
  mapId: string;
  name: string;
  description: string;
  shortDescription: string;
  zoneId: string;
  position: { x: number; y: number };
  nodeType: "start" | "milestone" | "checkpoint" | "legendary";
  icon: string;
  color: string;
  size: "small" | "medium" | "large";
  completeCondition: {
    type: string;
    value?: number;
    comparison: "gte" | "lte";
  };
  rewards: { xp: number };
  connectedTo: string[];
  connectedFrom: string[];
  isRequired: boolean;
  isAutoComplete: boolean;
  order: number;
  isActive: boolean;
  isSeasonal: boolean;
  requiredBadgeIds: string[];
  /**
   * The game(s) this milestone belongs to, or `undefined` for the platform map.
   *
   * Reason: `analyseMilestoneCoverage` credits a game-scoped condition with no
   * explicit list to **every** catalogue game, so without this one game's map
   * makes coverage read as complete for all of them.
   */
  gameTypes?: string[];
}

export interface BlueprintMap {
  mapId: string;
  name: string;
  description: string;
  zones: BlueprintZone[];
  defaultStartNode: string;
  backgroundColor: string;
  isActive: boolean;
  sequenceOrder: number;
  previousMapId: string | null;
  nextMapId: string | null;
  theme: MapTheme;
  difficulty: number;
  estimatedXP: number;
  requiredLevelToStart: number;
  completionRequirement: number;
  totalMilestones: number;
  /** The game this map belongs to, or `null` for the platform map. */
  gameKey: string | null;
}

export interface JourneyBlueprint {
  maps: BlueprintMap[];
  milestones: BlueprintMilestone[];
  /** XP the whole journey pays, for comparison against the level ladder. */
  totalXp: number;
}

/**
 * A milestone is worth more than a badge of the same tier, because it is a step
 * on a guided path rather than a shelf item — but it is paid in the **same**
 * currency, so the ladder can be derived from both together.
 */
const MILESTONE_XP_MULTIPLIER = 2;

const TIER_XP: readonly number[] = [
  DEFAULT_BADGE_XP.common * MILESTONE_XP_MULTIPLIER,
  DEFAULT_BADGE_XP.common * MILESTONE_XP_MULTIPLIER,
  DEFAULT_BADGE_XP.rare * MILESTONE_XP_MULTIPLIER,
  DEFAULT_BADGE_XP.rare * MILESTONE_XP_MULTIPLIER,
  DEFAULT_BADGE_XP.epic * MILESTONE_XP_MULTIPLIER,
  DEFAULT_BADGE_XP.epic * MILESTONE_XP_MULTIPLIER,
  DEFAULT_BADGE_XP.legendary * MILESTONE_XP_MULTIPLIER,
];

const ZONE_TEMPLATES: readonly {
  suffix: string;
  name: string;
  description: string;
  color: string;
  icon: string;
}[] = [
  {
    suffix: "foundations",
    name: "Foundations",
    description: "First steps — nothing here needs experience.",
    color: "#22C55E",
    icon: "flag",
  },
  {
    suffix: "ascent",
    name: "Ascent",
    description: "Consistency and volume start to matter.",
    color: "#3B82F6",
    icon: "mountain",
  },
  {
    suffix: "summit",
    name: "Summit",
    description: "The long targets, for players who stay.",
    color: "#A855F7",
    icon: "crown",
  },
];

/**
 * Themes are assigned by position rather than by game, deliberately.
 *
 * Reason: a theme picked from the game's own genre is per-game code in the one
 * layer that must not have any — it makes the "a new title needs no developer"
 * claim false for the first game whose genre is not in the list.
 */
const THEME_ROTATION: readonly MapTheme[] = [
  "ancient",
  "space",
  "medieval",
  "cyber",
  "pirate",
  "volcanic",
  "arctic",
  "dragon",
  "celestial",
  "legendary",
];

const NODE_ICONS: readonly string[] = [
  "flag",
  "starBadge",
  "shield1",
  "target",
  "goldMedal",
  "trophy",
  "crown",
];

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function nodeTypeFor(
  index: number,
  total: number,
): BlueprintMilestone["nodeType"] {
  if (index === 0) return "start";
  if (index === total - 1) return "legendary";
  // Reason: every fourth node is a checkpoint so the map has visible rhythm
  // without the caller having to nominate them.
  return (index + 1) % 4 === 0 ? "checkpoint" : "milestone";
}

function sizeFor(
  nodeType: BlueprintMilestone["nodeType"],
): BlueprintMilestone["size"] {
  if (nodeType === "legendary") return "large";
  if (nodeType === "checkpoint" || nodeType === "start") return "medium";
  return "small";
}

function describe(
  label: string,
  value: number | undefined,
  descending: boolean,
  percentage: boolean,
): string {
  if (value === undefined) return label;
  if (percentage) {
    return descending
      ? `Keep ${label.toLowerCase()} at or below ${value}%`
      : `Reach ${value}% ${label.toLowerCase()}`;
  }
  return descending
    ? `Finish ${label.toLowerCase()} at ${value} or better`
    : `Reach ${value} ${label.toLowerCase()}`;
}

/**
 * Lay a milestone out on a serpentine path so a map with any number of nodes
 * still reads as a route rather than a grid.
 *
 * Reason: the player renderer places nodes at absolute pixels on a 1200×800
 * canvas (`JourneyMapRenderer` MAP_WIDTH / MAP_HEIGHT). An earlier version of
 * this helper emitted values in the 10–90 range — which read as percentages —
 * so every node piled into a ~90×60 box in the top-left corner and the map
 * looked blank while the header still counted "1 of 12 milestones". Nothing
 * threw and nothing logged; the only witness was a screenshot.
 */
const MAP_LAYOUT_WIDTH = 1200;
const MAP_LAYOUT_HEIGHT = 800;

function positionFor(index: number, perRow = 5): { x: number; y: number } {
  const row = Math.floor(index / perRow);
  const col = index % perRow;
  // Reason: odd rows run right-to-left, which is what makes consecutive nodes
  // adjacent at a row boundary instead of jumping the full width of the map.
  const laidOut = row % 2 === 0 ? col : perRow - 1 - col;
  const marginX = 100;
  const marginY = 100;
  const usableW = MAP_LAYOUT_WIDTH - marginX * 2;
  const usableH = MAP_LAYOUT_HEIGHT - marginY * 2;
  const rowPitch = Math.min(160, Math.floor(usableH / 3));
  return {
    x: Math.round(marginX + laidOut * (usableW / Math.max(1, perRow - 1))),
    y: Math.round(marginY + row * rowPitch),
  };
}

function buildMilestonesForScope(
  quota: ScopeQuota,
  mapId: string,
  perMap: number,
): BlueprintMilestone[] {
  const defs = conditionsForScope(quota.scope);
  if (defs.length === 0 || perMap <= 0) return [];

  const isGameScope = quota.scope !== "platform";
  const gameName = isGameScope ? quota.label : null;
  const out: BlueprintMilestone[] = [];
  const used = new Set<string>();

  // Reason: walk tier-major rather than condition-major, so the candidate list is
  // ordered easiest-first across every condition rather than every rung of the
  // first one. A map whose only nodes are the hardest tier of a single condition
  // is unreachable and reads as a broken map.
  const candidates: { def: BadgeConditionDef; tier: number; value?: number }[] =
    [];
  for (let tier = 0; tier < TIER_XP.length; tier += 1) {
    for (const def of defs) {
      const boolean = isBooleanCondition(def);
      if (boolean && tier > 0) continue;
      const value = boolean ? undefined : thresholdFor(def.type, tier);
      if (!boolean && value === undefined) continue;
      candidates.push({ def, tier, value });
    }
  }

  // Reason: taking the first `perMap` candidates off a tier-major list gives a map
  // whose every node is tier 0 — twelve nodes worth the same XP, which is a flat
  // map with no sense of progress. Sampling evenly across the ordered list makes
  // the map START easy and END hard, which is what a journey is.
  const step = candidates.length > perMap ? candidates.length / perMap : 1;
  const picked =
    candidates.length > perMap
      ? Array.from(
          { length: perMap },
          (_, i) => candidates[Math.floor(i * step)],
        ).filter(
          (c): c is { def: BadgeConditionDef; tier: number; value?: number } =>
            c !== undefined,
        )
      : candidates;

  for (const { def, tier, value } of picked) {
    const base = def.label.replace(/\s*\(.*\)\s*/g, "").replace(/^Game\s+/, "");
    const id = `${mapId}_${slug(def.type)}${value === undefined ? "" : `_${value}`}`;
    if (used.has(id)) continue;
    used.add(id);

    const index = out.length;
    const nodeType = nodeTypeFor(index, perMap);
    const descending = DESCENDING_TYPES.has(def.type);
    const percentage = PERCENTAGE_TYPES.has(def.type);
    const zone = ZONE_TEMPLATES.at(
      Math.min(Math.floor(tier / 2), ZONE_TEMPLATES.length - 1),
    );
    const description = describe(base, value, descending, percentage);

    out.push({
      id,
      mapId,
      name: gameName ? `${gameName}: ${base}` : base,
      description: gameName
        ? `${description} in ${gameName}.`
        : `${description}.`,
      shortDescription: description,
      zoneId: `${mapId}_${zone?.suffix ?? "foundations"}`,
      position: positionFor(index),
      nodeType,
      icon: NODE_ICONS.at(Math.min(tier, NODE_ICONS.length - 1)) ?? "flag",
      color: zone?.color ?? "#3B82F6",
      size: sizeFor(nodeType),
      completeCondition: {
        type: def.type,
        ...(value === undefined ? {} : { value }),
        comparison: descending ? ("lte" as const) : ("gte" as const),
      },
      rewards: { xp: TIER_XP.at(tier) ?? TIER_XP[0] },
      connectedTo: [],
      connectedFrom: [],
      isRequired: nodeType !== "checkpoint",
      isAutoComplete: false,
      order: index,
      isActive: true,
      isSeasonal: false,
      requiredBadgeIds: [],
      ...(isGameScope ? { gameTypes: [quota.scope] } : {}),
    });
  }

  // Reason: the map renders edges from these two lists, so a blueprint that
  // leaves them empty produces a set of disconnected dots. They are wired after
  // the fact because a node cannot name its successor before it exists.
  for (let i = 0; i < out.length; i += 1) {
    const current = out.at(i);
    const next = out.at(i + 1);
    if (current && next) {
      current.connectedTo = [next.id];
      next.connectedFrom = [current.id];
    }
  }

  return out;
}

function zonesFor(mapId: string): BlueprintZone[] {
  return ZONE_TEMPLATES.map((z, i) => ({
    id: `${mapId}_${z.suffix}`,
    name: z.name,
    description: z.description,
    order: i,
    position: { x: 15 + i * 35, y: 50 },
    color: z.color,
    icon: z.icon,
    isUnlockable: i > 0,
  }));
}

export interface JourneyBlueprintOptions {
  /** Milestones per map. */
  perMap?: number;
  /** XP the badge catalogue pays, used only to gate later maps by level. */
  earnableBadgeXp?: number;
}

export const DEFAULT_MILESTONES_PER_MAP = 12;

/**
 * Build one map per scope in `plan`, plus its milestones.
 *
 * The plan is the same one the badges are built from, which is what guarantees a
 * game cannot have badges and no journey — the failure an operator sees as an
 * empty map after a reset.
 */
export function buildJourneyBlueprint(
  plan: BadgeQuotaPlan,
  options: JourneyBlueprintOptions = {},
): JourneyBlueprint {
  const perMap = Math.max(1, options.perMap ?? DEFAULT_MILESTONES_PER_MAP);
  const maps: BlueprintMap[] = [];
  const milestones: BlueprintMilestone[] = [];

  // Reason: the platform/"Getting Started" map was a journey with no game and
  // no trading — social/account conditions that produced a blank-looking route
  // (and that the owner does not want on the player carousel). Game and trading
  // scopes already cover every player; a third map for "platform" is friction
  // with no prize.
  const scopes = plan.scopes.filter(
    (s) => s.total > 0 && s.scope !== "platform",
  );

  scopes.forEach((quota, i) => {
    const mapId = `journey_${slug(quota.scope)}`;
    const scopeMilestones = buildMilestonesForScope(quota, mapId, perMap);
    if (scopeMilestones.length === 0) return;

    const estimatedXP = scopeMilestones.reduce(
      (sum, m) => sum + m.rewards.xp,
      0,
    );
    const bands = deriveLadderBands(
      (options.earnableBadgeXp ?? 0) + estimatedXP * scopes.length,
    );
    // Reason: the first map must be enterable at level 1 — a journey whose
    // opening map is gated is indistinguishable, from the player's seat, from
    // having no journey at all.
    const gateIndex = Math.min(i * 2, bands.length - 1);
    const requiredLevelToStart =
      i === 0 ? 1 : (bands.at(gateIndex)?.level ?? 1);

    maps.push({
      mapId,
      name: `${quota.label} Journey`,
      description: `Your path through ${quota.label}.`,
      zones: zonesFor(mapId),
      defaultStartNode: scopeMilestones[0]?.id ?? `${mapId}_start`,
      backgroundColor: "#0F172A",
      isActive: true,
      // Reason: `JourneyMapConfig.sequenceOrder` is capped at 10 by the schema,
      // so an eleventh map would fail validation and be dropped with the rest of
      // the run still reporting success. Clamping shares a position rather than
      // losing a game's journey; the chain below is what actually orders them.
      sequenceOrder: Math.min(10, i + 1),
      previousMapId: null,
      nextMapId: null,
      theme: THEME_ROTATION.at(i % THEME_ROTATION.length) ?? "ancient",
      difficulty: Math.min(10, 1 + i),
      estimatedXP,
      requiredLevelToStart,
      completionRequirement: 100,
      totalMilestones: scopeMilestones.length,
      gameKey: quota.scope === "trading" ? null : quota.scope,
    });
    milestones.push(...scopeMilestones);
  });

  // Reason: chained after the fact for the same reason the milestone edges are —
  // and a broken chain is silent, the player simply never being offered the next
  // map.
  for (let i = 0; i < maps.length; i += 1) {
    const current = maps.at(i);
    const next = maps.at(i + 1);
    if (current && next) {
      current.nextMapId = next.mapId;
      next.previousMapId = current.mapId;
    }
  }

  return {
    maps,
    milestones,
    totalXp: milestones.reduce((sum, m) => sum + m.rewards.xp, 0),
  };
}
