import type { GameIconName } from "@/lib/constants/game-icons";

export type BadgeCategory =
  | "Competition"
  | "Trading"
  | "Profit"
  | "Risk"
  | "Speed"
  | "Consistency"
  | "Strategy"
  | "Social"
  | "Legendary";

export interface Badge {
  id: string;
  name: string;
  description: string; // 2-3 words
  category: BadgeCategory;
  icon: GameIconName; // GameIcon name from game-icons.ts
  rarity: "common" | "rare" | "epic" | "legendary";
  condition: {
    type: string;
    value?: number;
    comparison?: "gte" | "lte" | "eq";
    // NEW: Minimum requirements to prevent zero-baseline badges
    minTrades?: number;
    minCompletedCompetitions?: number;
  };
}

export const BADGES: Badge[] = [
  // ============================================
  // COMPETITION BADGES - MASTERY (5+ entries, 3+ wins, 5+ podiums)
  // "First" achievements are handled by Journey Milestones only
  // ============================================
  {
    id: "comp_5_entries",
    name: "Competition Regular",
    description: "Joined 5 competitions",
    category: "Competition",
    icon: "trophy",
    rarity: "common",
    condition: { type: "competitions_entered", value: 5, comparison: "gte" },
  },
  {
    id: "comp_10_entries",
    name: "Competition Veteran",
    description: "Joined 10 competitions",
    category: "Competition",
    icon: "trophyStar",
    rarity: "rare",
    condition: { type: "competitions_entered", value: 10, comparison: "gte" },
  },
  {
    id: "comp_25_entries",
    name: "Competition Master",
    description: "Joined 25 competitions",
    category: "Competition",
    icon: "champion",
    rarity: "epic",
    condition: { type: "competitions_entered", value: 25, comparison: "gte" },
  },
  {
    id: "comp_50_entries",
    name: "Competition Legend",
    description: "Joined 50 competitions",
    category: "Competition",
    icon: "victory",
    rarity: "legendary",
    condition: { type: "competitions_entered", value: 50, comparison: "gte" },
  },
  {
    id: "comp_3_wins",
    name: "Champion",
    description: "Won 3 competitions",
    category: "Competition",
    icon: "crown",
    rarity: "rare",
    condition: { type: "first_place_finishes", value: 3, comparison: "gte" },
  },
  {
    id: "comp_5_wins",
    name: "Serial Winner",
    description: "Won 5 competitions",
    category: "Competition",
    icon: "goldMedal",
    rarity: "epic",
    condition: { type: "first_place_finishes", value: 5, comparison: "gte" },
  },
  {
    id: "comp_10_wins",
    name: "Dominator",
    description: "Won 10 competitions",
    category: "Competition",
    icon: "lightningSpell",
    rarity: "legendary",
    condition: { type: "first_place_finishes", value: 10, comparison: "gte" },
  },
  {
    id: "comp_5_podiums",
    name: "Podium Regular",
    description: "5 podium finishes",
    category: "Competition",
    icon: "trophy",
    rarity: "common",
    condition: { type: "podium_finishes", value: 5, comparison: "gte" },
  },
  {
    id: "comp_10_podiums",
    name: "Podium Pro",
    description: "10 podium finishes",
    category: "Competition",
    icon: "starAward",
    rarity: "rare",
    condition: { type: "podium_finishes", value: 10, comparison: "gte" },
  },
  {
    id: "comp_25_podiums",
    name: "Podium Legend",
    description: "25 podium finishes",
    category: "Competition",
    icon: "star1",
    rarity: "epic",
    condition: { type: "podium_finishes", value: 25, comparison: "gte" },
  },
  {
    id: "comp_perfect_run",
    name: "Perfect Run",
    description: "100% win rate",
    category: "Competition",
    icon: "champion",
    rarity: "legendary",
    condition: {
      type: "perfect_competition_win_rate",
      value: 100,
      comparison: "eq",
      minCompletedCompetitions: 3, // Must have completed at least 3 competitions
    },
  },
  {
    id: "comp_comeback",
    name: "Comeback King",
    description: "Won from behind",
    category: "Competition",
    icon: "crisisRecovery",
    rarity: "rare",
    condition: { type: "comeback_victory", minCompletedCompetitions: 1 },
  },
  {
    id: "comp_wire_to_wire",
    name: "Wire to Wire",
    description: "Led entire competition",
    category: "Competition",
    icon: "buy",
    rarity: "epic",
    condition: { type: "wire_to_wire_win", minCompletedCompetitions: 1 },
  },
  {
    id: "comp_giant_killer",
    name: "Giant Killer",
    description: "Beat top traders",
    category: "Competition",
    icon: "sword",
    rarity: "epic",
    condition: { type: "beat_top_trader", minCompletedCompetitions: 5 },
  },
  {
    id: "comp_underdog",
    name: "Underdog Victory",
    description: "Won as underdog",
    category: "Competition",
    icon: "wolf1",
    rarity: "rare",
    condition: { type: "underdog_win", minCompletedCompetitions: 1 },
  },
  {
    id: "comp_clean_sweep",
    name: "Clean Sweep",
    description: "Won all trades",
    category: "Competition",
    icon: "fireSpell",
    rarity: "legendary",
    condition: { type: "perfect_competition_trades", minTrades: 10, minCompletedCompetitions: 1 },
  },
  {
    id: "comp_marathon",
    name: "Marathon Runner",
    description: "Lasted full competition",
    category: "Competition",
    icon: "timer",
    rarity: "common",
    condition: { type: "survived_full_competition", minTrades: 10, minCompletedCompetitions: 1 },
  },
  {
    id: "comp_early_bird",
    name: "Early Bird",
    description: "First to trade",
    category: "Competition",
    icon: "star2",
    rarity: "common",
    condition: { type: "first_trade_in_comp", minTrades: 1, minCompletedCompetitions: 1 },
  },
  {
    id: "comp_night_owl",
    name: "Night Owl",
    description: "Traded late nights",
    category: "Competition",
    icon: "energySpell",
    rarity: "common",
    condition: { type: "late_night_trader", minTrades: 20 }, // Must have 20+ trades during night hours
  },

  // ============================================
  // TRADING VOLUME BADGES - MASTERY (25+ trades)
  // "First Trade" and early trades are Journey Milestones only
  // ============================================
  {
    id: "trade_25",
    name: "Active Trader",
    description: "Placed 25 trades",
    category: "Trading",
    icon: "trade",
    rarity: "common",
    condition: { type: "total_trades", value: 25, comparison: "gte" },
  },
  {
    id: "trade_50",
    name: "Frequent Trader",
    description: "Placed 50 trades",
    category: "Trading",
    icon: "portfolio",
    rarity: "common",
    condition: { type: "total_trades", value: 50, comparison: "gte" },
  },
  {
    id: "trade_100",
    name: "Century Mark",
    description: "Placed 100 trades",
    category: "Trading",
    icon: "starBadge",
    rarity: "rare",
    condition: { type: "total_trades", value: 100, comparison: "gte" },
  },
  {
    id: "trade_500",
    name: "Heavy Trader",
    description: "Placed 500 trades",
    category: "Trading",
    icon: "fireSpell",
    rarity: "epic",
    condition: { type: "total_trades", value: 500, comparison: "gte" },
  },
  {
    id: "trade_1000",
    name: "Trading Machine",
    description: "Placed 1000 trades",
    category: "Trading",
    icon: "joystick1",
    rarity: "legendary",
    condition: { type: "total_trades", value: 1000, comparison: "gte" },
  },
  {
    id: "trade_2500",
    name: "High Volume",
    description: "Placed 2500 trades",
    category: "Trading",
    icon: "headset",
    rarity: "legendary",
    condition: { type: "total_trades", value: 2500, comparison: "gte" },
  },
  {
    id: "trade_5000",
    name: "Ultra Trader",
    description: "Placed 5000 trades",
    category: "Trading",
    icon: "star3",
    rarity: "legendary",
    condition: { type: "total_trades", value: 5000, comparison: "gte" },
  },
  {
    id: "trade_day_trader",
    name: "Day Trader",
    description: "10+ trades daily",
    category: "Trading",
    icon: "timer",
    rarity: "rare",
    condition: { type: "daily_trade_volume", value: 10, comparison: "gte", minTrades: 25 },
  },
  {
    id: "trade_scalper",
    name: "Scalper",
    description: "50+ trades daily",
    category: "Trading",
    icon: "lightningSpell",
    rarity: "epic",
    condition: { type: "daily_trade_volume", value: 50, comparison: "gte", minTrades: 50 },
  },
  {
    id: "trade_marathon_session",
    name: "Marathon Session",
    description: "100+ trades single day",
    category: "Trading",
    icon: "war",
    rarity: "legendary",
    condition: { type: "single_day_trades", value: 100, comparison: "gte", minTrades: 100 },
  },
  {
    id: "trade_busy_week",
    name: "Busy Week",
    description: "100+ trades weekly",
    category: "Trading",
    icon: "flag",
    rarity: "rare",
    condition: { type: "weekly_trade_volume", value: 100, comparison: "gte", minTrades: 100 },
  },
  {
    id: "trade_monthly_grind",
    name: "Monthly Grinder",
    description: "500+ trades monthly",
    category: "Trading",
    icon: "banner",
    rarity: "epic",
    condition: { type: "monthly_trade_volume", value: 500, comparison: "gte", minTrades: 500 },
  },
  {
    id: "trade_diverse",
    name: "Diverse Trader",
    description: "Traded 10+ pairs",
    category: "Trading",
    icon: "maps",
    rarity: "rare",
    condition: { type: "unique_pairs_traded", value: 10, comparison: "gte", minTrades: 50 },
  },
  {
    id: "trade_specialist",
    name: "Pair Specialist",
    description: "100+ trades one pair",
    category: "Trading",
    icon: "target",
    rarity: "rare",
    condition: { type: "single_pair_focus", value: 100, comparison: "gte", minTrades: 100 },
  },

  // ============================================
  // PROFIT & LOSS BADGES - MASTERY (5+ wins, 25+ trades minimum)
  // "First Profit" is a Journey Milestone only
  // ============================================
  {
    id: "profit_5_wins",
    name: "Winning Trader",
    description: "Won 5 trades",
    category: "Profit",
    icon: "profit",
    rarity: "common",
    condition: { type: "winning_trades", value: 5, comparison: "gte", minTrades: 10 },
  },
  {
    id: "profit_10_wins",
    name: "Consistent Winner",
    description: "Won 10 trades",
    category: "Profit",
    icon: "gain",
    rarity: "common",
    condition: { type: "winning_trades", value: 10, comparison: "gte", minTrades: 15 },
  },
  {
    id: "profit_25_wins",
    name: "Profit Hunter",
    description: "Won 25 trades",
    category: "Profit",
    icon: "treasure",
    rarity: "rare",
    condition: { type: "winning_trades", value: 25, comparison: "gte", minTrades: 35 },
  },
  {
    id: "profit_50_wins",
    name: "Profit Master",
    description: "Won 50 trades",
    category: "Profit",
    icon: "chest",
    rarity: "epic",
    condition: { type: "winning_trades", value: 50, comparison: "gte", minTrades: 70 },
  },
  {
    id: "profit_100_wins",
    name: "Century Winner",
    description: "Won 100 trades",
    category: "Profit",
    icon: "crown",
    rarity: "legendary",
    condition: { type: "winning_trades", value: 100, comparison: "gte", minTrades: 130 },
  },
  {
    id: "profit_positive",
    name: "In The Green",
    description: "Positive total P&L",
    category: "Profit",
    icon: "dollarPlant",
    rarity: "common",
    condition: { type: "total_pnl_positive", minTrades: 25 }, // Must have 25+ trades first
  },
  {
    id: "profit_1k",
    name: "Thousand Club",
    description: "+1,000 total P&L",
    category: "Profit",
    icon: "money",
    rarity: "rare",
    condition: { type: "total_pnl", value: 1000, comparison: "gte", minTrades: 20 },
  },
  {
    id: "profit_5k",
    name: "Five K Club",
    description: "+5,000 total P&L",
    category: "Profit",
    icon: "coin",
    rarity: "epic",
    condition: { type: "total_pnl", value: 5000, comparison: "gte", minTrades: 50 },
  },
  {
    id: "profit_10k",
    name: "Ten K Club",
    description: "+10,000 total P&L",
    category: "Profit",
    icon: "gems",
    rarity: "legendary",
    condition: { type: "total_pnl", value: 10000, comparison: "gte", minTrades: 100 },
  },
  {
    id: "profit_big_win",
    name: "Big Winner",
    description: "+500 single trade",
    category: "Profit",
    icon: "chest",
    rarity: "rare",
    condition: { type: "single_trade_profit", value: 500, comparison: "gte" },
  },
  {
    id: "profit_huge_win",
    name: "Huge Winner",
    description: "+1000 single trade",
    category: "Profit",
    icon: "treasure",
    rarity: "epic",
    condition: { type: "single_trade_profit", value: 1000, comparison: "gte" },
  },
  {
    id: "profit_massive_win",
    name: "Massive Winner",
    description: "+2500 single trade",
    category: "Profit",
    icon: "star1",
    rarity: "legendary",
    condition: { type: "single_trade_profit", value: 2500, comparison: "gte" },
  },
  {
    id: "profit_win_streak_5",
    name: "Win Streak",
    description: "5 wins streak",
    category: "Profit",
    icon: "fireSpell",
    rarity: "common",
    condition: { type: "win_streak", value: 5, comparison: "gte", minTrades: 5 },
  },
  {
    id: "profit_win_streak_10",
    name: "Hot Streak",
    description: "10 wins streak",
    category: "Profit",
    icon: "blueFireSpell",
    rarity: "rare",
    condition: { type: "win_streak", value: 10, comparison: "gte", minTrades: 10 },
  },
  {
    id: "profit_win_streak_20",
    name: "Unstoppable",
    description: "20 wins streak",
    category: "Profit",
    icon: "buy",
    rarity: "epic",
    condition: { type: "win_streak", value: 20, comparison: "gte", minTrades: 20 },
  },
  {
    id: "profit_win_streak_50",
    name: "Legendary Streak",
    description: "50 wins streak",
    category: "Profit",
    icon: "crown",
    rarity: "legendary",
    condition: { type: "win_streak", value: 50, comparison: "gte", minTrades: 50 },
  },
  {
    id: "profit_roi_50",
    name: "Good Returns",
    description: "50%+ ROI",
    category: "Profit",
    icon: "profit",
    rarity: "rare",
    condition: { type: "average_roi", value: 50, comparison: "gte", minCompletedCompetitions: 3 },
  },
  {
    id: "profit_roi_100",
    name: "Double Up",
    description: "100%+ ROI",
    category: "Profit",
    icon: "returnOfInvest",
    rarity: "epic",
    condition: { type: "average_roi", value: 100, comparison: "gte", minCompletedCompetitions: 5 },
  },
  {
    id: "profit_roi_200",
    name: "Triple Threat",
    description: "200%+ ROI",
    category: "Profit",
    icon: "target",
    rarity: "legendary",
    condition: { type: "average_roi", value: 200, comparison: "gte", minCompletedCompetitions: 10 },
  },
  {
    id: "profit_factor_2",
    name: "Profitable Trader",
    description: "2.0+ profit factor",
    category: "Profit",
    icon: "star2",
    rarity: "rare",
    condition: { type: "profit_factor", value: 2, comparison: "gte", minTrades: 30 },
  },
  {
    id: "profit_factor_3",
    name: "Elite Trader",
    description: "3.0+ profit factor",
    category: "Profit",
    icon: "starAward",
    rarity: "epic",
    condition: { type: "profit_factor", value: 3, comparison: "gte", minTrades: 50 },
  },
  {
    id: "profit_factor_5",
    name: "Master Trader",
    description: "5.0+ profit factor",
    category: "Profit",
    icon: "star1",
    rarity: "legendary",
    condition: { type: "profit_factor", value: 5, comparison: "gte", minTrades: 100 },
  },
  {
    id: "profit_daily_green",
    name: "Daily Green",
    description: "Profitable every day",
    category: "Profit",
    icon: "dollarPlant",
    rarity: "epic",
    condition: {
      type: "consecutive_profitable_days",
      value: 7,
      comparison: "gte",
      minTrades: 20,
    },
  },
  {
    id: "profit_recovery",
    name: "Recovery Master",
    description: "Recovered from loss",
    category: "Profit",
    icon: "crisisRecovery",
    rarity: "rare",
    condition: { type: "drawdown_recovery", minTrades: 20 },
  },

  // ============================================
  // RISK MANAGEMENT BADGES (15)
  // ============================================
  {
    id: "risk_survivor",
    name: "Survivor",
    description: "Avoided liquidation",
    category: "Risk",
    icon: "shield1",
    rarity: "common",
    condition: { 
      type: "no_liquidations", 
      minCompletedCompetitions: 1, // MUST complete at least 1 competition
      minTrades: 5 // MUST have placed at least 5 trades
    },
  },
  {
    id: "risk_iron_man",
    name: "Iron Defense",
    description: "Never liquidated ever",
    category: "Risk",
    icon: "magicShield3D",
    rarity: "epic",
    condition: { 
      type: "zero_liquidations_lifetime",
      minCompletedCompetitions: 10, // MUST complete 10+ competitions
      minTrades: 50 // MUST have 50+ trades
    },
  },
  {
    id: "risk_low_drawdown",
    name: "Controlled Risk",
    description: "Max 10% drawdown",
    category: "Risk",
    icon: "riskControl",
    rarity: "rare",
    condition: { type: "max_drawdown", value: 10, comparison: "lte", minTrades: 30 },
  },
  {
    id: "risk_minimal_loss",
    name: "Minimal Losses",
    description: "Small average loss",
    category: "Risk",
    icon: "riskManagement",
    rarity: "rare",
    condition: { type: "average_loss_small", minTrades: 30 },
  },
  {
    id: "risk_stop_master",
    name: "Stop Loss Master",
    description: "Always uses stops",
    category: "Risk",
    icon: "riskWarning",
    rarity: "rare",
    condition: { type: "always_uses_sl", minTrades: 50 },
  },
  {
    id: "risk_tp_master",
    name: "Take Profit Pro",
    description: "Always uses TPs",
    category: "Risk",
    icon: "target",
    rarity: "rare",
    condition: { type: "always_uses_tp", minTrades: 50 },
  },
  {
    id: "risk_disciplined",
    name: "Disciplined Trader",
    description: "Follows risk rules",
    category: "Risk",
    icon: "riskAnalysis",
    rarity: "epic",
    condition: { type: "risk_discipline", minTrades: 50, minCompletedCompetitions: 5 },
  },
  {
    id: "risk_low_leverage",
    name: "Conservative",
    description: "Low leverage use",
    category: "Risk",
    icon: "shield2",
    rarity: "common",
    condition: { type: "average_leverage_low", minTrades: 20 },
  },
  {
    id: "risk_balanced",
    name: "Balanced Trader",
    description: "Optimal risk/reward",
    category: "Risk",
    icon: "equity",
    rarity: "rare",
    condition: { type: "balanced_risk_reward", minTrades: 40 },
  },
  {
    id: "risk_sharp",
    name: "Sharp Trader",
    description: "High Sharpe ratio",
    category: "Risk",
    icon: "swordNumbered",
    rarity: "epic",
    condition: { type: "sharpe_ratio_high", minTrades: 50 },
  },
  {
    id: "risk_steady",
    name: "Steady Eddie",
    description: "Low volatility",
    category: "Risk",
    icon: "healthPotion",
    rarity: "rare",
    condition: { type: "low_volatility", minTrades: 50 },
  },
  {
    id: "risk_calculated",
    name: "Calculated Risk",
    description: "Smart position sizing",
    category: "Risk",
    icon: "financialCalculation",
    rarity: "rare",
    condition: { type: "optimal_position_sizing", minTrades: 30 },
  },
  {
    id: "risk_diversified",
    name: "Diversified",
    description: "Multiple strategies",
    category: "Risk",
    icon: "portfolio",
    rarity: "rare",
    condition: { type: "strategy_diversity", minTrades: 50 },
  },
  {
    id: "risk_hedger",
    name: "Hedge Master",
    description: "Uses hedging",
    category: "Risk",
    icon: "hedge",
    rarity: "epic",
    condition: { type: "hedging_strategy", minTrades: 30 },
  },
  {
    id: "risk_safe_haven",
    name: "Safe Haven",
    description: "Low max drawdown",
    category: "Risk",
    icon: "armor1",
    rarity: "epic",
    condition: { type: "exceptional_dd_control", minTrades: 50 },
  },

  // ============================================
  // SPEED & EXECUTION BADGES (12)
  // ============================================
  {
    id: "speed_quick",
    name: "Quick Draw",
    description: "Fast order entry",
    category: "Speed",
    icon: "lightningSpell",
    rarity: "common",
    condition: { type: "fast_order_execution", minTrades: 20 },
  },
  {
    id: "speed_lightning",
    name: "Lightning Fast",
    description: "Sub-second execution",
    category: "Speed",
    icon: "lightningPotion",
    rarity: "rare",
    condition: { type: "ultra_fast_execution", minTrades: 10 },
  },
  {
    id: "speed_scalp_master",
    name: "Scalp Master",
    description: "Sub-minute trades",
    category: "Speed",
    icon: "timerAlt",
    rarity: "epic",
    condition: { type: "quick_scalps", minTrades: 50 },
  },
  {
    id: "speed_day_closer",
    name: "Day Closer",
    description: "Closes all daily",
    category: "Speed",
    icon: "timer",
    rarity: "rare",
    condition: { type: "closes_all_daily", minTrades: 30 },
  },
  {
    id: "speed_swing_trader",
    name: "Swing Trader",
    description: "Multi-day holds",
    category: "Speed",
    icon: "longTermInvestment",
    rarity: "common",
    condition: { type: "swing_trading_style", minTrades: 15 },
  },
  {
    id: "speed_position_trader",
    name: "Position Trader",
    description: "Week+ holds",
    category: "Speed",
    icon: "investment",
    rarity: "rare",
    condition: { type: "position_trading_style", minTrades: 10 },
  },
  {
    id: "speed_sniper",
    name: "Sniper",
    description: "Precise entries",
    category: "Speed",
    icon: "archer",
    rarity: "epic",
    condition: { type: "precise_entry_timing", minTrades: 40 },
  },
  {
    id: "speed_ninja",
    name: "Trading Ninja",
    description: "In-out quickly",
    category: "Speed",
    icon: "sword1",
    rarity: "rare",
    condition: { type: "ninja_trading", minTrades: 30 },
  },
  {
    id: "speed_patient",
    name: "Patient Trader",
    description: "Waits for setup",
    category: "Speed",
    icon: "helmet1",
    rarity: "rare",
    condition: { type: "patient_trading", minTrades: 20 },
  },
  {
    id: "speed_market_open",
    name: "Market Opener",
    description: "Trades at open",
    category: "Speed",
    icon: "flag",
    rarity: "common",
    condition: { type: "trades_at_open", minTrades: 20 },
  },
  {
    id: "speed_market_close",
    name: "Market Closer",
    description: "Trades at close",
    category: "Speed",
    icon: "key",
    rarity: "common",
    condition: { type: "trades_at_close", minTrades: 20 },
  },
  {
    id: "speed_24_7",
    name: "24/7 Trader",
    description: "All hours trading",
    category: "Speed",
    icon: "maps",
    rarity: "epic",
    condition: { type: "trades_all_hours", minTrades: 100 },
  },

  // ============================================
  // CONSISTENCY BADGES (10)
  // ============================================
  {
    id: "consist_daily",
    name: "Daily Consistency",
    description: "Trades every day",
    category: "Consistency",
    icon: "timer",
    rarity: "rare",
    condition: { type: "daily_trading_streak", value: 7, comparison: "gte", minTrades: 14 },
  },
  {
    id: "consist_weekly",
    name: "Weekly Warrior",
    description: "4 weeks straight",
    category: "Consistency",
    icon: "flag",
    rarity: "epic",
    condition: { type: "weekly_trading_streak", value: 4, comparison: "gte", minTrades: 40 },
  },
  {
    id: "consist_monthly",
    name: "Monthly Grinder",
    description: "3 months straight",
    category: "Consistency",
    icon: "banner",
    rarity: "legendary",
    condition: { type: "monthly_trading_streak", value: 3, comparison: "gte", minTrades: 100 },
  },
  {
    id: "consist_win_rate_60",
    name: "Consistent Winner",
    description: "60%+ win rate",
    category: "Consistency",
    icon: "starBadge",
    rarity: "rare",
    condition: { type: "win_rate", value: 60, comparison: "gte", minTrades: 50 },
  },
  {
    id: "consist_win_rate_70",
    name: "Elite Winner",
    description: "70%+ win rate",
    category: "Consistency",
    icon: "starAward",
    rarity: "epic",
    condition: { type: "win_rate", value: 70, comparison: "gte", minTrades: 75 },
  },
  {
    id: "consist_win_rate_80",
    name: "Master Winner",
    description: "80%+ win rate",
    category: "Consistency",
    icon: "crown",
    rarity: "legendary",
    condition: { type: "win_rate", value: 80, comparison: "gte", minTrades: 100 },
  },
  {
    id: "consist_stable",
    name: "Stable Returns",
    description: "Low variance",
    category: "Consistency",
    icon: "equity",
    rarity: "rare",
    condition: { type: "low_return_variance", minTrades: 50 },
  },
  {
    id: "consist_reliable",
    name: "Reliable Trader",
    description: "Predictable results",
    category: "Consistency",
    icon: "shield3",
    rarity: "epic",
    condition: { type: "predictable_results", minTrades: 75 },
  },
  {
    id: "consist_never_miss",
    name: "Never Miss",
    description: "Always active",
    category: "Consistency",
    icon: "fireSpell",
    rarity: "legendary",
    condition: { type: "perfect_attendance", minTrades: 200 },
  },
  {
    id: "consist_grind",
    name: "The Grind",
    description: "30+ day streak",
    category: "Consistency",
    icon: "lord",
    rarity: "legendary",
    condition: { type: "daily_trading_streak", value: 30, comparison: "gte", minTrades: 60 },
  },

  // ============================================
  // STRATEGY BADGES (10)
  // ============================================
  {
    id: "strat_trend",
    name: "Trend Follower",
    description: "Follows trends",
    category: "Strategy",
    icon: "profit",
    rarity: "common",
    condition: { type: "trend_following", minTrades: 30 },
  },
  {
    id: "strat_counter",
    name: "Counter Trader",
    description: "Trades reversals",
    category: "Strategy",
    icon: "crisisRecovery",
    rarity: "rare",
    condition: { type: "counter_trend", minTrades: 40 },
  },
  {
    id: "strat_breakout",
    name: "Breakout King",
    description: "Breakout specialist",
    category: "Strategy",
    icon: "bombNumbered",
    rarity: "rare",
    condition: { type: "breakout_trading", minTrades: 30 },
  },
  {
    id: "strat_range",
    name: "Range Trader",
    description: "Range bound",
    category: "Strategy",
    icon: "riskAnalysis",
    rarity: "common",
    condition: { type: "range_trading", minTrades: 40 },
  },
  {
    id: "strat_momentum",
    name: "Momentum Trader",
    description: "Rides momentum",
    category: "Strategy",
    icon: "buy",
    rarity: "rare",
    condition: { type: "momentum_trading", minTrades: 35 },
  },
  {
    id: "strat_mean_reversion",
    name: "Mean Reverter",
    description: "Mean reversion",
    category: "Strategy",
    icon: "equity",
    rarity: "rare",
    condition: { type: "mean_reversion", minTrades: 40 },
  },
  {
    id: "strat_news",
    name: "News Trader",
    description: "Trades news",
    category: "Strategy",
    icon: "guideBook",
    rarity: "epic",
    condition: { type: "news_trading", minTrades: 40 },
  },
  {
    id: "strat_technical",
    name: "Technical Analyst",
    description: "TA focused",
    category: "Strategy",
    icon: "financialCalculation",
    rarity: "common",
    condition: { type: "technical_analysis", minTrades: 50 },
  },
  {
    id: "strat_versatile",
    name: "Versatile Trader",
    description: "Multiple strategies",
    category: "Strategy",
    icon: "portfolio",
    rarity: "epic",
    condition: { type: "multiple_strategies", minTrades: 100 },
  },
  {
    id: "strat_original",
    name: "Original Style",
    description: "Unique approach",
    category: "Strategy",
    icon: "star1",
    rarity: "legendary",
    condition: { type: "unique_strategy", minTrades: 150 },
  },

  // ============================================
  // SOCIAL & ACHIEVEMENT BADGES - MASTERY (requires sustained activity)
  // "First Deposit" is a Journey Milestone only
  // ============================================
  {
    id: "social_early_adopter",
    name: "Early Adopter",
    description: "Joined early",
    category: "Social",
    icon: "star1",
    rarity: "rare",
    condition: { type: "early_adopter", minTrades: 10 },
  },
  {
    id: "social_3_months",
    name: "Seasoned Trader",
    description: "3 months active",
    category: "Social",
    icon: "pirateHat",
    rarity: "rare",
    condition: { type: "platform_age", value: 90, comparison: "gte", minTrades: 25 },
  },
  {
    id: "social_veteran",
    name: "Platform Veteran",
    description: "6 months active",
    category: "Social",
    icon: "starAward",
    rarity: "epic",
    condition: { type: "platform_age", value: 180, comparison: "gte", minTrades: 75 },
  },
  {
    id: "social_og",
    name: "OG Trader",
    description: "1 year active",
    category: "Social",
    icon: "lord",
    rarity: "legendary",
    condition: { type: "platform_age", value: 365, comparison: "gte", minTrades: 150 },
  },
  {
    id: "social_depositor",
    name: "Consistent Depositor",
    description: "Made 5+ deposits",
    category: "Social",
    icon: "moneyDeposit",
    rarity: "common",
    condition: { type: "total_deposits", value: 5, comparison: "gte" },
  },
  {
    id: "social_whale",
    name: "High Roller",
    description: "Large deposits",
    category: "Social",
    icon: "treasure",
    rarity: "epic",
    condition: { type: "total_deposited", value: 1000, comparison: "gte", minTrades: 25 },
  },
  {
    id: "social_cashout",
    name: "Cash Out King",
    description: "Made 3+ withdrawals",
    category: "Social",
    icon: "coin",
    rarity: "rare",
    condition: { type: "total_withdrawals", value: 3, comparison: "gte", minTrades: 25 },
  },
  {
    id: "social_big_cashout",
    name: "Big Winner Cashout",
    description: "Large withdrawal",
    category: "Social",
    icon: "gems",
    rarity: "epic",
    condition: { type: "large_withdrawal", minTrades: 50 },
  },
  {
    id: "social_net_positive",
    name: "Net Positive",
    description: "Withdrew more deposited",
    category: "Social",
    icon: "profit",
    rarity: "legendary",
    condition: { type: "net_profit_lifetime", minTrades: 75 },
  },

  // ============================================
  // LEGENDARY BADGES (10)
  // ============================================
  {
    id: "legend_perfect_month",
    name: "Perfect Month",
    description: "Flawless 30 days",
    category: "Legendary",
    icon: "crown",
    rarity: "legendary",
    condition: { type: "perfect_month", minTrades: 100 },
  },
  {
    id: "legend_million",
    name: "Millionaire",
    description: "1M total profit",
    category: "Legendary",
    icon: "treasure",
    rarity: "legendary",
    condition: { type: "total_pnl", value: 1000000, comparison: "gte", minTrades: 500 },
  },
  {
    id: "legend_rank_1",
    name: "Global Champion",
    description: "Rank #1 global",
    category: "Legendary",
    icon: "champion",
    rarity: "legendary",
    condition: { type: "global_rank", value: 1, comparison: "eq" },
  },
  {
    id: "legend_top_10",
    name: "Top 10 Trader",
    description: "Top 10 global",
    category: "Legendary",
    icon: "starAward",
    rarity: "legendary",
    condition: { type: "global_rank", value: 10, comparison: "lte" },
  },
  {
    id: "legend_top_100",
    name: "Elite 100",
    description: "Top 100 global",
    category: "Legendary",
    icon: "star2",
    rarity: "legendary",
    condition: { type: "global_rank", value: 100, comparison: "lte" },
  },
  {
    id: "legend_undefeated",
    name: "Undefeated",
    description: "100% competition wins",
    category: "Legendary",
    icon: "magicShield3D",
    rarity: "legendary",
    condition: { type: "undefeated_in_comps", minCompletedCompetitions: 10 },
  },
  {
    id: "legend_comeback",
    name: "Phoenix Trader",
    description: "Epic recovery",
    category: "Legendary",
    icon: "fireSpell",
    rarity: "legendary",
    condition: { type: "epic_comeback", minTrades: 100 },
  },
  {
    id: "legend_perfect_year",
    name: "Perfect Year",
    description: "Profitable 365 days",
    category: "Legendary",
    icon: "victory",
    rarity: "legendary",
    condition: { type: "perfect_year", minTrades: 500 },
  },
  {
    id: "legend_hall_of_fame",
    name: "Hall of Fame",
    description: "All-time great",
    category: "Legendary",
    icon: "champion",
    rarity: "legendary",
    condition: { type: "hall_of_fame_status", minTrades: 500, minCompletedCompetitions: 50 },
  },
  {
    id: "legend_immortal",
    name: "Immortal Trader",
    description: "Ultimate achievement",
    category: "Legendary",
    icon: "crown",
    rarity: "legendary",
    condition: { type: "all_legendary_badges", minTrades: 1000, minCompletedCompetitions: 100 },
  },
];

// Helper function to get badges by category
export const getBadgesByCategory = (category: BadgeCategory): Badge[] => {
  return BADGES.filter((badge) => badge.category === category);
};

// Helper function to get badges by rarity
export const getBadgesByRarity = (rarity: Badge["rarity"]): Badge[] => {
  return BADGES.filter((badge) => badge.rarity === rarity);
};

// Helper to get badge by ID
export const getBadgeById = (id: string): Badge | undefined => {
  return BADGES.find((badge) => badge.id === id);
};
