// 20 New Theme Presets for HeroSettings
// Matches the 20 new themes in lib/themes/landing-themes-new-1.ts and landing-themes-new-2.ts

import { IThemePreset } from "./hero-settings.interfaces";

export const newThemePresets: IThemePreset[] = [
  // ── Part 1: landing-themes-new-1.ts ────────────────────────────────────────
  {
    id: "samurai",
    name: "Samurai",
    description: "Japanese warrior honor and discipline",
    primaryColor: "#c62828",
    secondaryColor: "#ffd54f",
    accentColor: "#ff5252",
    backgroundColor: "#0d0505",
    gradientFrom: "#c62828",
    gradientTo: "#ff5252",
    fontFamily: "Noto Serif JP",
    buttonStyle: "gradient",
    cardStyle: "glassmorphism",
    animationStyle: "cinematic",
  },
  {
    id: "viking",
    name: "Viking",
    description: "Norse mythology and conquest",
    primaryColor: "#64b5f6",
    secondaryColor: "#ffab40",
    accentColor: "#ffd740",
    backgroundColor: "#0a1020",
    gradientFrom: "#64b5f6",
    gradientTo: "#ffab40",
    fontFamily: "Cinzel Decorative",
    buttonStyle: "gradient",
    cardStyle: "solid",
    animationStyle: "cinematic",
  },
  {
    id: "steampunk",
    name: "Steampunk",
    description: "Victorian industrial sci-fi aesthetics",
    primaryColor: "#d4a017",
    secondaryColor: "#cd7f32",
    accentColor: "#b87333",
    backgroundColor: "#0e0a05",
    gradientFrom: "#d4a017",
    gradientTo: "#b87333",
    fontFamily: "Playfair Display",
    buttonStyle: "solid",
    cardStyle: "solid",
    animationStyle: "minimal",
  },
  {
    id: "synthwave",
    name: "Synthwave",
    description: "80s retrowave neon sunset vibes",
    primaryColor: "#ff006e",
    secondaryColor: "#00d4ff",
    accentColor: "#ff8c00",
    backgroundColor: "#0d001a",
    gradientFrom: "#ff006e",
    gradientTo: "#00d4ff",
    fontFamily: "Orbitron",
    buttonStyle: "neon",
    cardStyle: "neon",
    animationStyle: "dynamic",
  },
  {
    id: "volcanic",
    name: "Volcanic",
    description: "Molten lava and magma eruption",
    primaryColor: "#ff4500",
    secondaryColor: "#ff8c00",
    accentColor: "#ffd700",
    backgroundColor: "#0a0000",
    gradientFrom: "#ff4500",
    gradientTo: "#ffd700",
    fontFamily: "Bebas Neue",
    buttonStyle: "glow",
    cardStyle: "gradient",
    animationStyle: "dynamic",
  },
  {
    id: "neon-tokyo",
    name: "Neon Tokyo",
    description: "Japanese neon cityscape at night",
    primaryColor: "#e91e63",
    secondaryColor: "#00bcd4",
    accentColor: "#ffeb3b",
    backgroundColor: "#05001a",
    gradientFrom: "#e91e63",
    gradientTo: "#00bcd4",
    fontFamily: "Rajdhani",
    buttonStyle: "neon",
    cardStyle: "neon",
    animationStyle: "dynamic",
  },
  {
    id: "pirate-bay",
    name: "Pirate Bay",
    description: "High seas treasure hunting adventure",
    primaryColor: "#1565c0",
    secondaryColor: "#ffd54f",
    accentColor: "#ff8f00",
    backgroundColor: "#0a1015",
    gradientFrom: "#1565c0",
    gradientTo: "#ffd54f",
    fontFamily: "Pirata One",
    buttonStyle: "gradient",
    cardStyle: "solid",
    animationStyle: "cinematic",
  },
  {
    id: "thunder-strike",
    name: "Thunder Strike",
    description: "Electric lightning storm energy",
    primaryColor: "#ffd700",
    secondaryColor: "#4fc3f7",
    accentColor: "#ffffff",
    backgroundColor: "#050510",
    gradientFrom: "#ffd700",
    gradientTo: "#4fc3f7",
    fontFamily: "Oswald",
    buttonStyle: "glow",
    cardStyle: "glassmorphism",
    animationStyle: "dynamic",
  },
  {
    id: "enchanted-forest",
    name: "Enchanted Forest",
    description: "Magical glowing forest wonderland",
    primaryColor: "#00e676",
    secondaryColor: "#b388ff",
    accentColor: "#ffeb3b",
    backgroundColor: "#001a0a",
    gradientFrom: "#00e676",
    gradientTo: "#b388ff",
    fontFamily: "Cinzel",
    buttonStyle: "gradient",
    cardStyle: "glassmorphism",
    animationStyle: "cinematic",
  },
  {
    id: "crystal-cave",
    name: "Crystal Cave",
    description: "Shimmering gems and crystals underground",
    primaryColor: "#7c4dff",
    secondaryColor: "#e040fb",
    accentColor: "#00e5ff",
    backgroundColor: "#08001a",
    gradientFrom: "#7c4dff",
    gradientTo: "#00e5ff",
    fontFamily: "Rajdhani",
    buttonStyle: "glow",
    cardStyle: "glassmorphism",
    animationStyle: "dynamic",
  },

  // ── Part 2: landing-themes-new-2.ts ────────────────────────────────────────
  {
    id: "pharaoh",
    name: "Pharaoh",
    description: "Ancient Egyptian gold and mystery",
    primaryColor: "#c6a300",
    secondaryColor: "#00897b",
    accentColor: "#ffd700",
    backgroundColor: "#0a0800",
    gradientFrom: "#c6a300",
    gradientTo: "#ffd700",
    fontFamily: "Cinzel Decorative",
    buttonStyle: "gradient",
    cardStyle: "solid",
    animationStyle: "cinematic",
  },
  {
    id: "jade-dragon",
    name: "Jade Dragon",
    description: "Imperial jade and dragon mythology",
    primaryColor: "#00c853",
    secondaryColor: "#ff6e40",
    accentColor: "#b9f6ca",
    backgroundColor: "#001a10",
    gradientFrom: "#00c853",
    gradientTo: "#b9f6ca",
    fontFamily: "Noto Serif SC",
    buttonStyle: "gradient",
    cardStyle: "solid",
    animationStyle: "cinematic",
  },
  {
    id: "blood-moon",
    name: "Blood Moon",
    description: "Crimson eclipse supernatural darkness",
    primaryColor: "#d50000",
    secondaryColor: "#880e4f",
    accentColor: "#ff8a80",
    backgroundColor: "#08000a",
    gradientFrom: "#d50000",
    gradientTo: "#880e4f",
    fontFamily: "Nosifer",
    buttonStyle: "glow",
    cardStyle: "solid",
    animationStyle: "dynamic",
  },
  {
    id: "aurora-borealis",
    name: "Aurora Borealis",
    description: "Northern lights celestial beauty",
    primaryColor: "#00bfa5",
    secondaryColor: "#76ff03",
    accentColor: "#7c4dff",
    backgroundColor: "#001020",
    gradientFrom: "#00bfa5",
    gradientTo: "#7c4dff",
    fontFamily: "Quicksand",
    buttonStyle: "gradient",
    cardStyle: "glassmorphism",
    animationStyle: "minimal",
  },
  {
    id: "desert-mirage",
    name: "Desert Mirage",
    description: "Golden dunes and shimmering heat haze",
    primaryColor: "#e6a44e",
    secondaryColor: "#5d4037",
    accentColor: "#f4d9a0",
    backgroundColor: "#120c05",
    gradientFrom: "#e6a44e",
    gradientTo: "#f4d9a0",
    fontFamily: "Playfair Display",
    buttonStyle: "solid",
    cardStyle: "solid",
    animationStyle: "minimal",
  },
  {
    id: "galactic-empire",
    name: "Galactic Empire",
    description: "Vast space empire and starship command",
    primaryColor: "#5c6bc0",
    secondaryColor: "#ff7043",
    accentColor: "#b0bec5",
    backgroundColor: "#000010",
    gradientFrom: "#5c6bc0",
    gradientTo: "#ff7043",
    fontFamily: "Orbitron",
    buttonStyle: "gradient",
    cardStyle: "glassmorphism",
    animationStyle: "cinematic",
  },
  {
    id: "venom",
    name: "Venom",
    description: "Toxic neon green on absolute black",
    primaryColor: "#00ff41",
    secondaryColor: "#76ff03",
    accentColor: "#b2ff59",
    backgroundColor: "#000000",
    gradientFrom: "#00ff41",
    gradientTo: "#76ff03",
    fontFamily: "Share Tech Mono",
    buttonStyle: "neon",
    cardStyle: "neon",
    animationStyle: "dynamic",
  },
  {
    id: "coral-reef",
    name: "Coral Reef",
    description: "Vibrant underwater tropical paradise",
    primaryColor: "#0097a7",
    secondaryColor: "#ff7043",
    accentColor: "#ffab91",
    backgroundColor: "#001520",
    gradientFrom: "#0097a7",
    gradientTo: "#ff7043",
    fontFamily: "Quicksand",
    buttonStyle: "gradient",
    cardStyle: "glassmorphism",
    animationStyle: "minimal",
  },
  {
    id: "midnight-jazz",
    name: "Midnight Jazz",
    description: "Smooth velvet lounge and golden spotlights",
    primaryColor: "#ce93d8",
    secondaryColor: "#ffd700",
    accentColor: "#ffab40",
    backgroundColor: "#0a0510",
    gradientFrom: "#ce93d8",
    gradientTo: "#ffd700",
    fontFamily: "Playfair Display",
    buttonStyle: "solid",
    cardStyle: "solid",
    animationStyle: "minimal",
  },
  {
    id: "iron-warlord",
    name: "Iron Warlord",
    description: "Dark iron and crimson conquest banners",
    primaryColor: "#bf360c",
    secondaryColor: "#455a64",
    accentColor: "#ff6d00",
    backgroundColor: "#080808",
    gradientFrom: "#bf360c",
    gradientTo: "#455a64",
    fontFamily: "Bebas Neue",
    buttonStyle: "solid",
    cardStyle: "solid",
    animationStyle: "dynamic",
  },
];
