/**
 * Plays a round to completion that SOMEBODY ELSE created.
 *
 * WHY THIS EXISTS, AND WHY NOT ONE OF THE THREE TOOLS THAT LOOK LIKE IT
 * --------------------------------------------------------------------
 * `smoke-play.ts`, `test-play.ts` and `test-board.ts` all play this game, and not one of them can
 * play a round the platform opened. Each boots its own in-memory MongoDB and creates its own round
 * inside it, which is the right shape for testing this service on its own and is precisely the
 * wrong shape for the one thing X4a exists to prove: that a round can travel between the two
 * halves. Chapter 21 puts it plainly - the two halves are built and **have never spoken to each
 * other** - and every tool here was on the wrong side of that sentence.
 *
 * So this takes a `roundId` that already exists in whatever database this service is pointed at,
 * and plays it through the same four HTTP endpoints the browser uses. No shortcuts: it opens a
 * session, reads the state, submits paths, and stops when the server says the round is over. The
 * server decides the score, exactly as it does for a human.
 *
 *   npx tsx tools/autoplay.ts --round=cv_rnd_abc123
 *   npx tsx tools/autoplay.ts --round=cv_rnd_abc123 --base=http://127.0.0.1:4010
 *   npx tsx tools/autoplay.ts --round=cv_rnd_abc123 --slow=800   # lose on purpose, for the
 *                                                                # lower-is-better title
 *
 * IT IS A PERFECT PLAYER, AND THAT IS A LIMITATION TO STATE RATHER THAN A FEATURE
 * ------------------------------------------------------------------------------
 * It reads the generator's own solution out of the round's seeds, so it never fails a board and
 * never draws an invalid path. That makes it useless for testing the verifier - `test-engine.ts`
 * and `test-board.ts` own that - and ideal for driving the money: a contest needs somebody to
 * finish, and a run that sometimes loses cannot assert a payout.
 *
 * READING THE SOLUTION IS SAFE HERE FOR THE SAME REASON `--reveal` IS
 * ------------------------------------------------------------------
 * Section 12 forbids exposing a seed to a player and there is deliberately no endpoint that
 * returns content for one. This is not an endpoint. It is a local tool, run from a terminal by
 * somebody who already has the database credentials, and **nothing here is reachable over HTTP**.
 * If a future change makes any of this answer a request, that is the line being crossed.
 */

import { generateForPlayer } from "../src/engine/generate";
import type { Cell } from "../src/engine/puzzle";
import { shapeFor, type GridSize } from "../src/games/titles";
import { connectToDatabase, disconnectFromDatabase } from "../src/store/db";
import { Round } from "../src/store/round.model";

interface ClientBoard {
  index: number;
  width: number;
  height: number;
  pairs: { id: number; a: Cell; b: Cell }[];
}

interface PlayState {
  roundId: string;
  gameCode: string;
  status: string;
  board?: ClientBoard;
  boardsSolved: number;
  boardTarget?: number;
  endsAt?: string;
  finished?: { status: string; boardsSolved: number };
}

/**
 * Only `submit` wraps its state; `session`, `state` and `leave` return a bare `PlayState`.
 *
 * That asymmetry is real and it is in `src/http/play-routes.ts` - `postSession` does
 * `res.json(state)` while `postSubmit` does `res.json(outcome)`. The first version of this tool
 * assumed all four were wrapped, and the symptom was `Session refused: unknown`: reading `.state`
 * off a bare state gives `undefined`, which is indistinguishable from a refusal. **A response
 * shape read from a summary is a hypothesis until a real response disagrees with it.**
 */
interface SubmitResponse {
  accepted?: boolean;
  refusal?: string;
  message?: string;
  state: PlayState;
}

function arg(name: string): string | undefined {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : undefined;
}

/**
 * The board's solution, computed the way the server would.
 *
 * `presentationSeed` is generated by this service and stored only here, so the platform cannot
 * derive this - which is the reason this tool has to live on this side of the wall rather than in
 * the platform's test suite.
 */
async function solutionFor(
  roundId: string,
  boardIndex: number,
): Promise<{ pairId: number; cells: Cell[] }[]> {
  const round = await Round.findOne({ roundId });
  if (!round) throw new Error(`No round ${roundId} in this database.`);

  const config = round.config as { gridSize: GridSize };
  const generated = generateForPlayer(
    round.contentSeed ?? round.providerRoundId,
    round.presentationSeed,
    boardIndex,
    shapeFor(config.gridSize),
  );

  return generated.pairs.map((pair, index) => ({
    pairId: pair.id,
    // One path per pair by construction, and `index` is the callback's own counter.
    // eslint-disable-next-line security/detect-object-injection
    cells: generated.solution[index],
  }));
}

async function post<T>(base: string, path: string, body: unknown): Promise<T> {
  const response = await fetch(`${base}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const text = await response.text();
  if (response.status !== 200) {
    throw new Error(`${path} -> ${response.status}: ${text}`);
  }
  return JSON.parse(text) as T;
}

async function main(): Promise<void> {
  const roundId = arg("round");
  if (!roundId) {
    console.error("Usage: npx tsx tools/autoplay.ts --round=<roundId> [--base=<url>] [--slow=<ms>]");
    process.exit(2);
  }

  const base = (arg("base") ?? `http://127.0.0.1:${process.env.PORT ?? 4010}`).replace(/\/+$/, "");
  const slowMs = Number.parseInt(arg("slow") ?? "", 10) || 0;

  await connectToDatabase();

  try {
    const round = await Round.findOne({ roundId });
    if (!round) throw new Error(`No round ${roundId} in this database.`);
    const token = round.launchToken;

    /*
     * The token is taken from the database rather than from a launch URL handed in on the command
     * line, and that is deliberate. A caller that already has the URL has been told the token, so
     * accepting it would let this tool play a round whose seeds it cannot read - which would fail
     * later, at the first submission, with a puzzle mismatch that reads like an engine bug.
     */
    let state = await post<PlayState>(base, "/play/api/session", { t: token });
    if (state.finished) {
      throw new Error(
        `Round is already over before play began: ${state.finished.status}. ` +
          `A launched round should be startable - check the contest play window.`,
      );
    }

    console.log(`▶️  ${state.gameCode} ${roundId} - status ${state.status}`);

    let submissions = 0;
    // A ceiling rather than `while (true)`: a server bug that never advances the board would
    // otherwise spin for ever inside a test suite and report as a timeout with no board count.
    const MAX_SUBMISSIONS = 400;

    /*
     * THE TWO TITLES END FOR DIFFERENT REASONS, AND ONLY ONE OF THEM ENDS BECAUSE YOU PLAYED WELL.
     *
     * `circuit-perfect` asks for a fixed number of boards, so solving them finishes the round.
     * `circuit-sprint` asks how many you can solve in a fixed time, so **a perfect player never
     * finishes it** - the clock does, and the sweeper writes the terminal status up to one tick
     * later. The first version of this loop ignored `endsAt` and kept submitting, which read as an
     * infinite loop and cost a test run to diagnose.
     *
     * So: play while there is time, then stop and let the server end it. Nothing here writes a
     * terminal status, which is correct - the client is an input device.
     */
    const deadline = state.endsAt ? new Date(state.endsAt).getTime() : null;
    const timeLeft = () => (deadline === null ? Infinity : deadline - Date.now());

    while (!state.finished && submissions < MAX_SUBMISSIONS && timeLeft() > 1_500) {
      const board = state.board;
      if (!board) throw new Error(`No board to play in status ${state.status}.`);

      if (slowMs > 0) await new Promise((resolve) => setTimeout(resolve, slowMs));

      const paths = await solutionFor(roundId, board.index);
      const answer = await post<SubmitResponse>(base, "/play/api/submit", {
        t: token,
        boardIndex: board.index,
        paths,
      });
      submissions += 1;

      if (!answer.state) throw new Error(`Submit returned no state: ${answer.refusal ?? "?"}`);
      if (answer.accepted === false) {
        // Worth failing loudly rather than retrying. A perfect player being refused means the
        // seeds this tool read and the puzzle the server built have diverged, which is a real
        // defect and not a bad guess.
        throw new Error(`Board ${board.index} refused: ${answer.refusal} - ${answer.message}`);
      }

      state = answer.state;
      console.log(`   board ${board.index} solved (${state.boardsSolved}/${state.boardTarget ?? "?"})`);
    }

    /*
     * A timed round is still running here. Poll the state until the server agrees it is over -
     * this is the browser's own behaviour when a clock expires, and it is what proves the sweeper
     * closes a run-out clock rather than leaving the round in flight.
     */
    if (!state.finished) {
      const giveUp = Date.now() + Math.max(timeLeft(), 0) + 30_000;
      while (!state.finished && Date.now() < giveUp) {
        await new Promise((resolve) => setTimeout(resolve, 500));
        const response = await fetch(`${base}/play/api/state?t=${encodeURIComponent(token)}`);
        if (response.status !== 200) {
          throw new Error(`state -> ${response.status}: ${await response.text()}`);
        }
        state = (await response.json()) as PlayState;
      }
    }

    if (!state.finished) throw new Error(`Round did not finish after ${submissions} submissions.`);

    /*
     * The score is deliberately NOT printed from here, because this tool cannot know it. A finished
     * state carries only the status and the board count - the score travels in the signed callback
     * to the platform and nowhere else. Printing a number here would invite somebody to assert on
     * it, and the assertion would be reading the client's opinion of a server-owned value.
     */
    console.log(`✅ ${roundId} finished - ${state.finished.status}, ${state.finished.boardsSolved} boards`);
  } finally {
    await disconnectFromDatabase();
  }
}

main().catch((error) => {
  console.error(`❌ autoplay failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
