"""
Measure where the cell grid sits inside every board skin and write `public/play/skin-geometry.js`.

Why this exists: every skin in the deck (`board-s/m/l-NN.webp`) draws its grid at a different
place inside its frame. Positioning all of them with one set of insets per grid size put the
numbers visibly off the drawn cells on most boards.

How: cell borders are strong edges and cell centres are flat, so the edge-strength profile along
each axis is a comb with `n + 1` teeth. The script searches every period and offset for the comb
that best separates "on a line" from "in a cell centre", with a mild centring prior to break ties.

Usage (from games-service/):
    python tools/measure-board-skins.py              # rewrite skin-geometry.js
    python tools/measure-board-skins.py --overlay DIR  # also write overlay sheets to check by eye

Re-run whenever a skin is added or replaced, and check the overlays: a wrong figure here puts the
wires and numbers a few pixels off the drawn cells on every board that wears that skin.
"""
import glob
import os
import sys

import numpy as np
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
PLAY = os.path.normpath(os.path.join(HERE, "..", "public", "play"))
OUT = os.path.join(PLAY, "skin-geometry.js")
CELLS = {"s": 4, "m": 6, "l": 8}
S = 627  # working size; the files are 1254 square


def profile(lum, axis):
    h, w = lum.shape
    if axis == 0:
        g = np.pad(np.abs(np.diff(lum, axis=1)), ((0, 0), (0, 1)))
        p = g[int(h * 0.25):int(h * 0.75), :].mean(axis=0)
    else:
        g = np.pad(np.abs(np.diff(lum, axis=0)), ((0, 1), (0, 0)))
        p = g[:, int(w * 0.25):int(w * 0.75)].mean(axis=1)
    return np.convolve(p, np.ones(7) / 7, mode="same")


def fit(p, n):
    L = len(p)
    xs = np.arange(L)
    best = None
    for period in np.arange(L * 0.5 / n, L * 0.95 / n, 0.25):
        span = period * n
        offsets = np.arange(0, L - span, 0.5)
        if len(offsets) == 0:
            continue
        lines = offsets[:, None] + np.arange(0, n + 1)[None, :] * period
        cents = offsets[:, None] + (np.arange(n) + 0.5)[None, :] * period
        score = np.interp(lines, xs, p).mean(axis=1) - np.interp(cents, xs, p).mean(axis=1)
        asym = np.abs(offsets - (L - offsets - span)) / L
        score = score - 0.15 * asym * p.mean()
        i = int(np.argmax(score))
        if best is None or score[i] > best[0]:
            best = (score[i], offsets[i], period)
    return best[1], best[2]


def measure(path):
    n = CELLS[os.path.basename(path)[6]]
    im = Image.open(path).convert("RGB").resize((S, S), Image.LANCZOS)
    lum = np.asarray(im).astype(float).mean(axis=2)
    ox, px = fit(profile(lum, 0), n)
    oy, py = fit(profile(lum, 1), n)
    gw, gh = px * n, py * n
    insets = dict(
        top=oy / gh,
        right=(S - ox - gw) / gw,
        bottom=(S - oy - gh) / gh,
        left=ox / gw,
    )
    return n, (ox, px, oy, py), insets, im


def main():
    overlay_dir = None
    if "--overlay" in sys.argv:
        overlay_dir = sys.argv[sys.argv.index("--overlay") + 1]
    files = sorted(glob.glob(os.path.join(PLAY, "board-[sml]-*.webp")))
    rows = []
    thumbs = []
    for f in files:
        n, (ox, px, oy, py), ins, im = measure(f)
        name = "/play/" + os.path.basename(f)
        rows.append((name, n, ins))
        if overlay_dir:
            dr = ImageDraw.Draw(im)
            for k in range(n + 1):
                dr.line([(ox + k * px, oy), (ox + k * px, oy + py * n)], fill=(255, 0, 255), width=5)
                dr.line([(ox, oy + k * py), (ox + px * n, oy + k * py)], fill=(255, 0, 255), width=5)
            im.thumbnail((300, 300))
            thumbs.append((os.path.basename(f), im))

    lines = [
        "// GENERATED by tools/measure-board-skins.py - do not edit by hand; re-run the script.",
        "//",
        "// Where the drawn cell grid sits inside each board skin, as a fraction of the grid's own",
        "// extent on that axis (same convention as DRAWN_BOARD_FRAMES in presentation.js). A Map",
        "// because the key is a URL the server sent, and an object lookup walks the prototype chain.",
        "export const SKIN_GEOMETRY = new Map([",
    ]
    for name, n, ins in rows:
        lines.append(
            '  ["%s", { cells: %d, top: %.4f, right: %.4f, bottom: %.4f, left: %.4f }],'
            % (name, n, ins["top"], ins["right"], ins["bottom"], ins["left"])
        )
    lines.append("]);")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", OUT, len(rows), "skins")

    if overlay_dir:
        os.makedirs(overlay_dir, exist_ok=True)
        for page in range(0, len(thumbs), 12):
            chunk = thumbs[page:page + 12]
            sheet = Image.new("RGB", (4 * 300, ((len(chunk) + 3) // 4) * 316))
            d2 = ImageDraw.Draw(sheet)
            for i, (name, im) in enumerate(chunk):
                x, y = (i % 4) * 300, (i // 4) * 316
                sheet.paste(im, (x, y + 16))
                d2.text((x + 2, y + 2), name, fill=(255, 255, 0))
            sheet.save(os.path.join(overlay_dir, "skins-%d.jpg" % (page // 12)), quality=85)


main()
