"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const mongoose_1 = require("mongoose");
const FraudAlertSchema = new mongoose_1.Schema({
    alertType: {
        type: String,
        required: true,
        enum: [
            'same_device',
            'same_ip',
            'same_ip_browser',
            'mirror_trading',
            'same_payment',
            'coordinated_entry',
            'suspicious_behavior',
            'vpn_usage',
            'high_risk_device'
        ]
    },
    severity: {
        type: String,
        required: true,
        enum: ['low', 'medium', 'high', 'critical'],
        default: 'medium'
    },
    status: {
        type: String,
        required: true,
        enum: ['pending', 'investigating', 'resolved', 'dismissed'],
        default: 'pending'
    },
    // Related entities
    competitionId: String,
    suspiciousUserIds: { type: [String], required: true, index: true },
    primaryUserId: { type: String, required: true }, // Index defined separately below
    // Evidence
    confidence: { type: Number, required: true, min: 0, max: 1 },
    evidence: [{
            type: { type: String, required: true },
            description: { type: String, required: true },
            data: mongoose_1.Schema.Types.Mixed
        }],
    // Details
    title: { type: String, required: true },
    description: { type: String, required: true },
    detectedAt: { type: Date, default: Date.now },
    // Resolution
    resolvedAt: Date,
    resolvedBy: String,
    resolution: String,
    actionTaken: {
        type: String,
        enum: ['none', 'warning', 'account_suspended', 'account_banned', 'prize_withheld']
    },
    // Metadata
    autoGenerated: { type: Boolean, default: true },
    notificationSent: { type: Boolean, default: false },
}, {
    timestamps: true
});
// Indexes for fast queries
FraudAlertSchema.index({ status: 1, severity: -1 });
FraudAlertSchema.index({ competitionId: 1 });
FraudAlertSchema.index({ detectedAt: -1 });
FraudAlertSchema.index({ primaryUserId: 1 });
const FraudAlert = mongoose_1.models.FraudAlert || (0, mongoose_1.model)('FraudAlert', FraudAlertSchema);
exports.default = FraudAlert;
//# sourceMappingURL=fraud-alert.model.js.map