import { Schema, model, models, Document } from 'mongoose';

export type FraudAlertType = 
  | 'same_device'           // Multiple accounts on same device
  | 'same_ip'               // Multiple accounts from same IP
  | 'same_ip_browser'       // Multiple accounts from same IP + same browser
  | 'mirror_trading'        // Opposite trades at same time
  | 'same_payment'          // Same payment method used
  | 'coordinated_entry'     // Accounts created/entered at same time
  | 'suspicious_behavior'   // Other suspicious patterns
  | 'vpn_usage'             // VPN/Proxy detected
  | 'high_risk_device';     // Device with high risk score

export type AlertStatus = 'pending' | 'investigating' | 'resolved' | 'dismissed';
export type AlertSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface IFraudAlert extends Document {
  alertType: FraudAlertType;
  severity: AlertSeverity;
  status: AlertStatus;
  
  // Related entities
  competitionId?: string;
  suspiciousUserIds: string[];
  primaryUserId: string; // The main user being flagged
  
  // Evidence
  confidence: number; // 0-1, how confident we are this is fraud
  evidence: {
    type: string;
    description: string;
    data: any;
  }[];
  
  // Details
  title: string;
  description: string;
  detectedAt: Date;
  
  // Resolution
  resolvedAt?: Date;
  resolvedBy?: string; // Admin user ID
  resolution?: string;
  actionTaken?: 'none' | 'warning' | 'account_suspended' | 'account_banned' | 'prize_withheld';
  
  // Metadata
  autoGenerated: boolean;
  notificationSent: boolean;
  
  createdAt: Date;
  updatedAt: Date;
}

const FraudAlertSchema = new Schema<IFraudAlert>({
  alertType: { 
    type: String, 
    required: true,
    enum: [
      'same_device',
      'same_ip',
      'same_ip_browser',
      'mirror_trading',
      'same_payment',
      'coordinated_entry',
      'suspicious_behavior',
      'vpn_usage',
      'high_risk_device'
    ]
  },
  severity: { 
    type: String, 
    required: true,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'medium'
  },
  status: { 
    type: String, 
    required: true,
    enum: ['pending', 'investigating', 'resolved', 'dismissed'],
    default: 'pending'
  },
  
  // Related entities
  competitionId: String,
  suspiciousUserIds: { type: [String], required: true, index: true },
  primaryUserId: { type: String, required: true }, // Index defined separately below
  
  // Evidence
  confidence: { type: Number, required: true, min: 0, max: 1 },
  evidence: [{
    type: { type: String, required: true },
    description: { type: String, required: true },
    data: Schema.Types.Mixed
  }],
  
  // Details
  title: { type: String, required: true },
  description: { type: String, required: true },
  detectedAt: { type: Date, default: Date.now },
  
  // Resolution
  resolvedAt: Date,
  resolvedBy: String,
  resolution: String,
  actionTaken: {
    type: String,
    enum: ['none', 'warning', 'account_suspended', 'account_banned', 'prize_withheld']
  },
  
  // Metadata
  autoGenerated: { type: Boolean, default: true },
  notificationSent: { type: Boolean, default: false },
}, {
  timestamps: true
});

// Indexes for fast queries
FraudAlertSchema.index({ status: 1, severity: -1 });
FraudAlertSchema.index({ competitionId: 1 });
FraudAlertSchema.index({ detectedAt: -1 });
FraudAlertSchema.index({ primaryUserId: 1 });

const FraudAlert = models.FraudAlert || model<IFraudAlert>('FraudAlert', FraudAlertSchema);

export default FraudAlert;

