import { Document } from 'mongoose';
export type FraudAlertType = 'same_device' | 'same_ip' | 'same_ip_browser' | 'mirror_trading' | 'same_payment' | 'coordinated_entry' | 'suspicious_behavior' | 'vpn_usage' | 'high_risk_device';
export type AlertStatus = 'pending' | 'investigating' | 'resolved' | 'dismissed';
export type AlertSeverity = 'low' | 'medium' | 'high' | 'critical';
export interface IFraudAlert extends Document {
    alertType: FraudAlertType;
    severity: AlertSeverity;
    status: AlertStatus;
    competitionId?: string;
    suspiciousUserIds: string[];
    primaryUserId: string;
    confidence: number;
    evidence: {
        type: string;
        description: string;
        data: any;
    }[];
    title: string;
    description: string;
    detectedAt: Date;
    resolvedAt?: Date;
    resolvedBy?: string;
    resolution?: string;
    actionTaken?: 'none' | 'warning' | 'account_suspended' | 'account_banned' | 'prize_withheld';
    autoGenerated: boolean;
    notificationSent: boolean;
    createdAt: Date;
    updatedAt: Date;
}
declare const FraudAlert: import("mongoose").Model<any, {}, {}, {}, any, any>;
export default FraudAlert;
//# sourceMappingURL=fraud-alert.model.d.ts.map